// <auto-generated/>
using System.Globalization;
using Blazor_PersianDatePickerZO.Component;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using NetTopologySuite.Geometries;
using RMS.Client.Components;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.AccidentsLogging;

public partial class Accidents
{
    private static readonly EntityColumn[] columns =
    [
        new("Code", "شناسه"), new("Road", "راه یا محدوده"), new("Type", "نوع حادثه"),
    new("Weather", "وضعیت جوی"), new("People", "افراد درگیر"), new("Date", "زمان وقوع")
    ];

    private readonly List<EntityRow> rows = [];
    private readonly Dictionary<string, string> draft = new(StringComparer.OrdinalIgnoreCase);
    private int totalCount;
    private EntityListPanel? listPanel;
    private EntityRow? editingRow;
    private EntityRow? deletingRow;
    private DotNetObjectReference<Accidents>? accidentMapReference;
    private bool isLoading = true;
    private bool modalOpen;
    private bool deleteModalOpen;
    private bool isLoadingEditor;
    private bool isMutating;
    private bool accidentMapPending;
    private bool isLocating;
    private Guid? selectedAccidentRoadId;
    private double? selectedLatitude;
    private double? selectedLongitude;
    private double? gpsAccuracy;
    private Geometry? selectedRoadGeometry;
    private string? pageError;
    private string? locationError;
    private string? mutationError;
    private string? deleteError;
    private string? successMessage;
    private DateTime accidentDatePicker = DateTime.Now;
    private DatePickerZO? accidentDatePickerComponent;
    private DateTime filterMonth = DateTime.Now;
    private YearMonthZO? filterMonthPickerComponent;
    private string selectedRoad = string.Empty;
    private Guid? filterRoadId;

    private bool CanList => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Create);
    private bool CanUpdate => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.View)
        && AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Delete);
    private bool CanListCars => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);
    private bool CanListPeople => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);
    private bool CanListImages => AuthenticationState.HasPermission(UserSection.Images, UserAccessOperation.Report);

    protected override async Task OnInitializedAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }
        isLoading = false;
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!accidentMapPending)
            return;

        accidentMapPending = false;
        accidentMapReference ??= DotNetObjectReference.Create(this);
        var rendered = await JS.InvokeAsync<bool>(
            "rmsInterop.renderAccidentLocationMap",
            "accident-location-map",
            BuildSelectedRoadPaths(),
            selectedLatitude.HasValue && selectedLongitude.HasValue
                ? new MapPoint(selectedLatitude.Value, selectedLongitude.Value)
                : null,
            accidentMapReference);
        if (!rendered)
            accidentMapPending = true;
    }

    private async Task LoadAsync()
    {
        if (!filterRoadId.HasValue)
        {
            rows.Clear();
            totalCount = 0;
            isLoading = false;
            return;
        }

        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(new EntityPageRequest(0, 20, string.Empty, CancellationToken.None));
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت حوادث از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadPageAsync(EntityPageRequest request)
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(request);
        }
        catch (OperationCanceledException) when (request.CancellationToken.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت حوادث از API با خطا مواجه شد.");
        }
        finally
        {
            if (!request.CancellationToken.IsCancellationRequested)
                isLoading = false;
        }
    }

    private async Task LoadPageCoreAsync(EntityPageRequest request)
    {
        var result = await AccidentApi.GetAllAsync(new AccidentQuery
        {
            StartTime = AccidentFilterHelper.GetPersianMonthRange(filterMonth).StartTime,
            EndTime = AccidentFilterHelper.GetPersianMonthRange(filterMonth).EndTime,
            RoadId = filterRoadId,
            Skip = request.Skip,
            Take = request.Take,
            SearchTerm = request.SearchTerm,
            OrderBy = AccidentSortOrder.AccidentTimeDescending
        }, request.CancellationToken);
        rows.Clear();
        rows.AddRange(result.Items.Select(ToRow));
        totalCount = result.TotalCount;
    }

    private async Task<IReadOnlyList<LookupOption>> SearchRoadsAsync(string term, CancellationToken token) =>
        (await LookupApi.GetRoadsAsync(new LookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(road => new LookupOption(road.Id.ToString(), road.Name))
            .ToArray();

    private async Task OpenCreateAsync()
    {
        editingRow = null;
        draft.Clear();
        AccidentDatePicker = DateTime.Now;
        mutationError = null;
        isLoadingEditor = false;
        modalOpen = true;
        await PrepareEditorAsync();
    }

    /// <summary>راه فیلتر حوادث را انتخاب و فهرست همان راه را بارگذاری می‌کند.</summary>
    private async Task SelectFilterRoadAsync(string value)
    {
        selectedRoad = value;
        filterRoadId = Guid.TryParse(value, out var roadId) ? roadId : null;
        rows.Clear();
        totalCount = 0;
        await LoadAsync();
    }

    /// <summary>ماه فیلتر را از تقویم فارسی دریافت و فهرست را تازه می‌کند.</summary>
    private async Task OnFilterMonthChanged()
    {
        filterMonth = filterMonthPickerComponent?.SelectDate ?? DateTime.Now;
        if (filterRoadId.HasValue)
            await LoadAsync();
    }

    private async Task OpenEditAsync(EntityRow row)
    {
        editingRow = row;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = true;
        modalOpen = true;
        try
        {
            foreach (var item in ToDraft(await AccidentApi.GetByIdAsync(row.Id)))
                draft[item.Key] = item.Value;
            SyncAccidentDatePickerFromDraft();
            await PrepareEditorAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "دریافت جزئیات حادثه با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private async Task PrepareEditorAsync()
    {
        selectedAccidentRoadId = ParseRoadId(draft);
        selectedLatitude = ParseCoordinate(draft, "Latitude");
        selectedLongitude = ParseCoordinate(draft, "Longitude");
        gpsAccuracy = null;
        locationError = null;
        isLocating = false;
        await LoadSelectedRoadGeometryAsync();
        accidentMapPending = true;
        await InvokeAsync(StateHasChanged);
    }

    private async Task ChangeRoadAsync(string value)
    {
        draft["Road"] = value;
        var roadId = ParseRoadId(draft);
        if (roadId == selectedAccidentRoadId)
            return;

        selectedAccidentRoadId = roadId;
        selectedLatitude = null;
        selectedLongitude = null;
        gpsAccuracy = null;
        locationError = null;
        isLocating = false;
        draft["Latitude"] = string.Empty;
        draft["Longitude"] = string.Empty;
        await LoadSelectedRoadGeometryAsync();
        accidentMapPending = true;
        await InvokeAsync(StateHasChanged);
    }

    private async Task CloseModalAsync()
    {
        if (isMutating)
            return;
        modalOpen = false;
        await ResetEditorAsync();
    }

    private async Task ResetEditorAsync()
    {
        accidentMapPending = false;
        selectedAccidentRoadId = null;
        selectedLatitude = null;
        selectedLongitude = null;
        selectedRoadGeometry = null;
        gpsAccuracy = null;
        locationError = null;
        isLocating = false;
        await JS.InvokeVoidAsync("rmsInterop.disposeAccidentLocationMap");
    }

    private async Task SaveAsync()
    {
        mutationError = null;
        isMutating = true;
        try
        {
            if (editingRow is null)
            {
                await CreateAsync(draft);
                successMessage = "حادثه با موفقیت ثبت شد.";
            }
            else
            {
                await UpdateAsync(editingRow.Id, draft);
                successMessage = "حادثه با موفقیت ویرایش شد.";
            }

            modalOpen = false;
            await ResetEditorAsync();
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "ذخیره اطلاعات حادثه با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private void AskDelete(EntityRow row)
    {
        deletingRow = row;
        deleteError = null;
        deleteModalOpen = true;
    }

    private void CloseDeleteModal()
    {
        if (!isMutating)
            deleteModalOpen = false;
    }

    private async Task ConfirmDeleteAsync()
    {
        if (deletingRow is null)
            return;

        deleteError = null;
        isMutating = true;
        try
        {
            await DeleteAsync(deletingRow.Id);
            deleteModalOpen = false;
            successMessage = "حادثه با موفقیت حذف شد.";
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            deleteError = ErrorMessage(exception, "حذف حادثه با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private async Task UseCurrentLocationAsync()
    {
        locationError = null;
        isLocating = true;
        await JS.InvokeVoidAsync("rmsInterop.useCurrentAccidentLocation");
    }

    private async Task ClearAccidentLocationAsync()
    {
        selectedLatitude = null;
        selectedLongitude = null;
        gpsAccuracy = null;
        locationError = null;
        draft["Latitude"] = string.Empty;
        draft["Longitude"] = string.Empty;
        await JS.InvokeVoidAsync("rmsInterop.clearAccidentLocation");
    }

    [JSInvokable]
    public async Task OnAccidentLocationChanged(double latitude, double longitude, double? accuracy)
    {
        if (!selectedAccidentRoadId.HasValue)
            return;

        try
        {
            var nearest = await RoadApi.GetNearestPointAsync(
                selectedAccidentRoadId.Value,
                latitude,
                longitude);
            if (!nearest.IsWithinTolerance)
            {
                isLocating = false;
                locationError = $"نقطه انتخاب‌شده {nearest.DistanceMeters.ToString("0", CultureInfo.InvariantCulture).TranslateDigits()} متر از مسیر فاصله دارد. نقطه‌ای نزدیک‌تر از ۱۰۰ متر انتخاب کنید.";
                await JS.InvokeVoidAsync("rmsInterop.clearAccidentLocation");
                await InvokeAsync(StateHasChanged);
                return;
            }

            latitude = nearest.NearestLatitude;
            longitude = nearest.NearestLongitude;
            await JS.InvokeVoidAsync("rmsInterop.setAccidentLocation", latitude, longitude);
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            isLocating = false;
            locationError = ErrorMessage(exception, "اعتبارسنجی موقعیت حادثه روی مسیر با خطا مواجه شد.");
            await InvokeAsync(StateHasChanged);
            return;
        }

        selectedLatitude = latitude;
        selectedLongitude = longitude;
        gpsAccuracy = accuracy;
        locationError = null;
        isLocating = false;
        draft["Latitude"] = latitude.ToString("G17", CultureInfo.InvariantCulture);
        draft["Longitude"] = longitude.ToString("G17", CultureInfo.InvariantCulture);
        await InvokeAsync(StateHasChanged);
    }

    [JSInvokable]
    public async Task OnAccidentGeolocationError(int errorCode)
    {
        isLocating = false;
        locationError = errorCode switch
        {
            1 => "اجازه دسترسی به موقعیت مکانی داده نشد. دسترسی Location مرورگر را فعال کنید.",
            2 => "موقعیت دستگاه در دسترس نیست. GPS یا سرویس مکان‌یابی را بررسی کنید.",
            3 => "دریافت موقعیت بیش از حد طول کشید. دوباره تلاش کنید.",
            _ => "مرورگر یا دستگاه امکان دریافت موقعیت مکانی را فراهم نکرد."
        };
        await InvokeAsync(StateHasChanged);
    }

    private Task CreateAsync(IReadOnlyDictionary<string, string> values) => AccidentApi.CreateAsync(new CreateAccidentCommand
    {
        FkIdRoad = FormValues.Guid(values, "Road", "راه یا محدوده"),
        AccidentTimeUnix = FormValues.UnixTime(values, "Date", "زمان وقوع"),
        Latitude = FormValues.Double(values, "Latitude", "عرض جغرافیایی"),
        Longitude = FormValues.Double(values, "Longitude", "طول جغرافیایی"),
        Weather = FormValues.Enum<WeatherConditionEnums>(values, "Weather", "وضعیت آب‌وهوا"),
        RoadCondition = FormValues.Enum<RoadConditionEnums>(values, "RoadCondition", "وضعیت سطح راه"),
        LightingCondition = FormValues.Enum<LightingConditionEnums>(values, "Lighting", "وضعیت روشنایی"),
        TrafficSignCondition = FormValues.Enum<TrafficSignConditionEnums>(values, "Sign", "وضعیت علائم"),
        AccidentCause = FormValues.Enum<AccidentCauseEnums>(values, "Cause", "علت حادثه"),
        AccidentType = FormValues.Enum<AccidentTypeEnums>(values, "Type", "نوع برخورد")
    });

    private Task UpdateAsync(Guid id, IReadOnlyDictionary<string, string> values) => AccidentApi.UpdateAsync(id, new UpdateAccidentCommand
    {
        Id = id,
        FkIdRoad = FormValues.Guid(values, "Road", "راه یا محدوده"),
        AccidentTimeUnix = FormValues.UnixTime(values, "Date", "زمان وقوع"),
        Latitude = FormValues.Double(values, "Latitude", "عرض جغرافیایی"),
        Longitude = FormValues.Double(values, "Longitude", "طول جغرافیایی"),
        Weather = FormValues.Enum<WeatherConditionEnums>(values, "Weather", "وضعیت آب‌وهوا"),
        RoadCondition = FormValues.Enum<RoadConditionEnums>(values, "RoadCondition", "وضعیت سطح راه"),
        LightingCondition = FormValues.Enum<LightingConditionEnums>(values, "Lighting", "وضعیت روشنایی"),
        TrafficSignCondition = FormValues.Enum<TrafficSignConditionEnums>(values, "Sign", "وضعیت علائم"),
        AccidentCause = FormValues.Enum<AccidentCauseEnums>(values, "Cause", "علت حادثه"),
        AccidentType = FormValues.Enum<AccidentTypeEnums>(values, "Type", "نوع برخورد")
    });

    private Task DeleteAsync(Guid id) => AccidentApi.DeleteAsync(id);

    private static EntityRow ToRow(AccidentListItemResponse accident) => new()
    {
        Id = accident.Id,
        Status = accident.InjuryPercentage >= 70 ? "شدید" : accident.InjuryPercentage >= 30 ? "متوسط" : "ثبت‌شده",
        StatusTone = RmsUi.InjuryTone(accident.InjuryPercentage),
        Values = new()
        {
            ["Code"] = $"ACC-{RmsUi.ShortId(accident.Id)}",
            ["Road"] = accident.RoadName,
            ["Type"] = RmsUi.AccidentType(accident.AccidentType),
            ["Weather"] = RmsUi.Weather(accident.Weather),
            ["People"] = $"{accident.PeopleCount.ToString().TranslateDigits()} نفر",
            ["Date"] = RmsUi.DateTime(accident.AccidentTimeUnix),
        }
    };

    private static IReadOnlyDictionary<string, string> ToDraft(AccidentResponse accident) =>
        new Dictionary<string, string>
        {
            ["Road"] = accident.FkIdRoad.ToString(),
            ["Date"] = RmsUi.DateTimeInput(accident.AccidentTimeUnix),
            ["Latitude"] = accident.Latitude.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["Longitude"] = accident.Longitude.ToString(System.Globalization.CultureInfo.InvariantCulture),
            ["Weather"] = Convert.ToByte(accident.Weather).ToString(),
            ["RoadCondition"] = Convert.ToByte(accident.RoadCondition).ToString(),
            ["Lighting"] = Convert.ToByte(accident.LightingCondition).ToString(),
            ["Sign"] = Convert.ToByte(accident.TrafficSignCondition).ToString(),
            ["Cause"] = Convert.ToByte(accident.AccidentCause).ToString(),
            ["Type"] = Convert.ToByte(accident.AccidentType).ToString()
        };

    private static LookupOption[] EnumOptions<TEnum>(Func<TEnum, string> label)
        where TEnum : struct, Enum => Enum.GetValues<TEnum>()
            .Select(value => new LookupOption(Convert.ToByte(value).ToString(), label(value)))
            .ToArray();

    private string CoordinateLabel => selectedLatitude.HasValue && selectedLongitude.HasValue
        ? $"{selectedLatitude.Value.ToString("0.000000", CultureInfo.InvariantCulture)}, {selectedLongitude.Value.ToString("0.000000", CultureInfo.InvariantCulture)}"
        : string.Empty;

    private static Guid? ParseRoadId(IReadOnlyDictionary<string, string> values) =>
        values.TryGetValue("Road", out var value) && Guid.TryParse(value, out var roadId) ? roadId : null;

    private static double? ParseCoordinate(IReadOnlyDictionary<string, string> values, string key) =>
        values.TryGetValue(key, out var value)
        && double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out var coordinate)
            ? coordinate
            : null;

    private IReadOnlyList<IReadOnlyList<MapPoint>> BuildSelectedRoadPaths()
        => selectedRoadGeometry is null ? [] : RoutePaths(selectedRoadGeometry);

    private async Task LoadSelectedRoadGeometryAsync()
    {
        selectedRoadGeometry = null;
        if (!selectedAccidentRoadId.HasValue)
            return;

        try
        {
            selectedRoadGeometry = (await RoadApi.GetGeometryAsync(selectedAccidentRoadId.Value)).Boundary;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            locationError = ErrorMessage(exception, "دریافت هندسه راه انتخاب‌شده با خطا مواجه شد.");
        }
    }

    private static IReadOnlyList<IReadOnlyList<MapPoint>> RoutePaths(Geometry geometry)
    {
        static IReadOnlyList<MapPoint> ConvertCoordinates(Coordinate[] coordinates)
        {
            if (coordinates.Length > 1 && coordinates[0].Equals2D(coordinates[^1]))
                coordinates = coordinates[..^1];
            return coordinates
                .Select(coordinate => new MapPoint(coordinate.Y, coordinate.X))
                .ToArray();
        }

        return geometry switch
        {
            LineString lineString => [ConvertCoordinates(lineString.Coordinates)],
            MultiLineString multiLineString => Enumerable.Range(0, multiLineString.NumGeometries)
                .Select(index => (IReadOnlyList<MapPoint>)ConvertCoordinates(
                    ((LineString)multiLineString.GetGeometryN(index)).Coordinates))
                .ToArray(),
            Polygon polygon => [ConvertCoordinates(polygon.ExteriorRing.Coordinates)],
            MultiPolygon multiPolygon => Enumerable.Range(0, multiPolygon.NumGeometries)
                .Select(index => (IReadOnlyList<MapPoint>)ConvertCoordinates(
                    ((Polygon)multiPolygon.GetGeometryN(index)).ExteriorRing.Coordinates))
                .ToArray(),
            _ => [ConvertCoordinates(geometry.Coordinates)]
        };
    }

    private string GetDraft(string key) => draft.GetValueOrDefault(key, string.Empty);
    private void SetDraft(string key, object? value) => draft[key] = value?.ToString() ?? string.Empty;
    private DateTime AccidentDatePicker
    {
        get => accidentDatePicker;
        set
        {
            accidentDatePicker = value;
            draft["Date"] = value.ToString("yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture);
        }
    }

    private void SyncAccidentDatePickerFromDraft()
    {
        if (DateTime.TryParseExact(GetDraft("Date"), "yyyy-MM-ddTHH:mm", CultureInfo.InvariantCulture,
            DateTimeStyles.None, out var value))
        {
            accidentDatePicker = value;
        }
    }

    private void OnAccidentDateChanged()
    {
        if (accidentDatePickerComponent is not null)
            AccidentDatePicker = accidentDatePickerComponent.SelectDate ?? DateTime.Now;
    }
    private void ChangeWeather(ChangeEventArgs eventArgs) => SetDraft("Weather", eventArgs.Value);
    private void ChangeRoadCondition(ChangeEventArgs eventArgs) => SetDraft("RoadCondition", eventArgs.Value);
    private void ChangeLighting(ChangeEventArgs eventArgs) => SetDraft("Lighting", eventArgs.Value);
    private void ChangeSign(ChangeEventArgs eventArgs) => SetDraft("Sign", eventArgs.Value);
    private void ChangeCause(ChangeEventArgs eventArgs) => SetDraft("Cause", eventArgs.Value);
    private void ChangeType(ChangeEventArgs eventArgs) => SetDraft("Type", eventArgs.Value);

    private static bool IsExpectedException(Exception exception) =>
        exception is ApiClientException or HttpRequestException or FormatException or InvalidOperationException or ArgumentException;

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ => fallback
    };

    public async ValueTask DisposeAsync()
    {
        try
        {
            await JS.InvokeVoidAsync("rmsInterop.disposeAccidentLocationMap");
        }
        catch (JSDisconnectedException)
        {
        }
        accidentMapReference?.Dispose();
        accidentMapReference = null;
    }

    private sealed record MapPoint(double Latitude, double Longitude);
}
