// <auto-generated/>
using System.Globalization;
using Blazor_PersianDatePickerZO.Component;
using Microsoft.AspNetCore.Components;
using RMS.Client.Components;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.AccidentsLogging;

public partial class Cars
{
    [Parameter]
    public Guid? AccidentId
    {
        get; set;
    }

    private static readonly EntityColumn[] scopedColumns =
    [
        new("Plate", "شماره پلاک"), new("Car", "خودرو"), new("Class", "کلاس"),
    new("Year", "سال تولید"), new("Damage", "خسارت")
    ];

    private readonly List<EntityRow> rows = [];
    private readonly Dictionary<string, string> draft = new(StringComparer.OrdinalIgnoreCase);
    private EntityListPanel? listPanel;
    private AccidentResponse? ParentAccident;
    private EntityRow? editingRow;
    private EntityRow? deletingRow;
    private int totalCount;
    private bool isLoading = true;
    private bool modalOpen;
    private bool deleteModalOpen;
    private bool isLoadingEditor;
    private bool isMutating;
    private string? pageError;
    private string? mutationError;
    private string? deleteError;
    private string? successMessage;
    private DateTime licenseDatePicker = DateTime.Today;
    private DatePickerZO? licenseDatePickerComponent;

    private IReadOnlyList<EntityColumn> Columns => scopedColumns;
    private string PageTitleText => AccidentId.HasValue ? $"خودروهای حادثه ACC-{RmsUi.ShortId(AccidentId.Value)}" : "انتخاب حادثه برای خودروها";
    private string PageDescription => AccidentId.HasValue
        ? "ثبت و مدیریت خودروهای همین حادثه؛ شناسه حادثه به‌صورت خودکار اعمال می‌شود."
        : "برای مشاهده یا ثبت خودرو، ابتدا از فهرست حوادث یک حادثه را انتخاب کنید.";

    private bool CanList => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Create);
    private bool CanCreateHere => CanCreate && AccidentId.HasValue && ParentAccident is not null;
    private bool CanUpdate => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.View)
        && AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Delete);
    private bool CanListAccidents => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
    private bool CanListPassengers => AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.Report);
    private bool CanListPeople => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);


    /// <summary>راه والد را انتخاب می‌کند تا جستجوی حادثه محدود شود.</summary>
    /// <summary>شناسه حادثه انتخاب‌شده را دریافت و به مسیر خودروها هدایت می‌کند.</summary>
    private Task HandleAccidentSelectedAsync(Guid? accidentId)
    {
        if (accidentId.HasValue)
            Navigation.NavigateTo($"/accidents/{accidentId.Value}/cars");
        return Task.CompletedTask;
    }

    /*
    private Task SelectRoadAsync(string value)
    {
        selectedRoad = value;
        filterRoadId = Guid.TryParse(value, out var roadId) ? roadId : null;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    /// <summary>ماه فیلتر حادثه را از تقویم فارسی دریافت می‌کند.</summary>
    private Task OnFilterMonthChanged()
    {
        filterMonth = filterMonthPickerComponent?.SelectDate ?? DateTime.Now;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    private Task SelectAccidentAsync(string value)
    {
        if (Guid.TryParse(value, out var accidentId))
            Navigation.NavigateTo($"/accidents/{accidentId}/cars");
        return Task.CompletedTask;
    }

    private async Task<IReadOnlyList<LookupOption>> SearchAccidentsAsync(string term, CancellationToken token)
    {
        if (!filterRoadId.HasValue)
            return (await LookupApi.GetRoadsAsync(new LookupQuery { SearchTerm = term, Take = 20 }, token))
                .Select(road => new LookupOption(road.Id.ToString(), road.Name)).ToArray();

        return await AccidentFilterHelper.SearchAccidentsAsync(AccidentApi, filterRoadId, filterMonth, term, token);
    }


    */

    protected override async Task OnParametersSetAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }

        ParentAccident = null;
        pageError = null;
        if (AccidentId.HasValue)
        {
            try
            {
                ParentAccident = await AccidentApi.GetByIdAsync(AccidentId.Value);
            }
            catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
            {
                pageError = ErrorMessage(exception, "دریافت اطلاعات حادثه با خطا مواجه شد.");
                isLoading = false;
                rows.Clear();
                totalCount = 0;
                return;
            }
        }
        else
        {
            rows.Clear();
            totalCount = 0;
            isLoading = false;
            return;
        }

        await LoadAsync();
    }

    private async Task LoadAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(new EntityPageRequest(0, 20, string.Empty, CancellationToken.None));
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت خودروها از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadPageAsync(EntityPageRequest request)
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(request);
        }
        catch (OperationCanceledException) when (request.CancellationToken.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت خودروها از API با خطا مواجه شد.");
        }
        finally
        {
            if (!request.CancellationToken.IsCancellationRequested)
                isLoading = false;
        }
    }

    private async Task LoadPageCoreAsync(EntityPageRequest request)
    {
        if (!AccidentId.HasValue)
        {
            rows.Clear();
            totalCount = 0;
            return;
        }

        var result = await CarApi.GetAllAsync(new CarQueries
        {
            AccidentId = AccidentId.Value,
            Skip = request.Skip,
            Take = request.Take,
            SearchTerm = request.SearchTerm
        }, request.CancellationToken);
        rows.Clear();
        rows.AddRange(result.Items.Select(ToRow));
        totalCount = result.TotalCount;
    }

    private void OpenCreate()
    {
        if (!CanCreateHere)
            return;
        editingRow = null;
        draft.Clear();
        LicenseDatePicker = DateTime.Today;
        mutationError = null;
        isLoadingEditor = false;
        modalOpen = true;
    }

    private async Task OpenEditAsync(EntityRow row)
    {
        editingRow = row;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = true;
        modalOpen = true;
        try
        {
            foreach (var item in ToDraft(await CarApi.GetByIdAsync(row.Id)))
                draft[item.Key] = item.Value;
            SyncLicenseDatePickerFromDraft();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "دریافت جزئیات خودرو با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private void CloseModal()
    {
        if (!isMutating)
            modalOpen = false;
    }

    private async Task SaveAsync()
    {
        mutationError = null;
        isMutating = true;
        try
        {
            if (editingRow is null)
            {
                if (!AccidentId.HasValue)
                    throw new InvalidOperationException("ثبت خودرو باید از صفحه حادثه انجام شود.");
                await CreateAsync(AccidentId.Value, draft);
                successMessage = "خودرو با موفقیت برای این حادثه ثبت شد.";
            }
            else
            {
                await UpdateAsync(editingRow.Id, draft);
                successMessage = "خودرو با موفقیت ویرایش شد.";
            }

            modalOpen = false;
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "ذخیره اطلاعات خودرو با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private void AskDelete(EntityRow row)
    {
        deletingRow = row;
        deleteError = null;
        deleteModalOpen = true;
    }

    private void CloseDeleteModal()
    {
        if (!isMutating)
            deleteModalOpen = false;
    }

    private async Task ConfirmDeleteAsync()
    {
        if (deletingRow is null)
            return;
        deleteError = null;
        isMutating = true;
        try
        {
            await CarApi.DeleteAsync(deletingRow.Id);
            deleteModalOpen = false;
            successMessage = "خودرو با موفقیت حذف شد.";
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            deleteError = ErrorMessage(exception, "حذف خودرو با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private Task CreateAsync(Guid accidentId, IReadOnlyDictionary<string, string> values) => CarApi.CreateAsync(new CreateCarCommand
    {
        FkAccident = accidentId,
        PlateNumber = FormValues.Required(values, "Plate", "شماره پلاک"),
        CarName = FormValues.Required(values, "Car", "نام خودرو"),
        CarClass = FormValues.Enum<CarClassEnums>(values, "Class", "رده خودرو"),
        ProductionYear = FormValues.Int(values, "Year", "سال تولید"),
        Color = FormValues.Optional(values, "Color"),
        DriverPhone = FormValues.Required(values, "DriverPhone", "شماره تماس راننده"),
        DriverLicNumber = FormValues.Required(values, "License", "شماره گواهینامه"),
        DateLic = FormValues.Date(values, "LicenseDate", "تاریخ صدور گواهینامه"),
        DateLicValidity = FormValues.Byte(values, "LicenseValidity", "اعتبار گواهینامه"),
        DamagePercentage = FormValues.Byte(values, "Damage", "درصد خسارت")
    });

    private Task UpdateAsync(Guid id, IReadOnlyDictionary<string, string> values) => CarApi.UpdateAsync(id, new UpdateCarCommand
    {
        Id = id,
        PlateNumber = FormValues.Required(values, "Plate", "شماره پلاک"),
        CarName = FormValues.Required(values, "Car", "نام خودرو"),
        CarClass = FormValues.Enum<CarClassEnums>(values, "Class", "رده خودرو"),
        ProductionYear = FormValues.Int(values, "Year", "سال تولید"),
        Color = FormValues.Optional(values, "Color"),
        DriverPhone = FormValues.Required(values, "DriverPhone", "شماره تماس راننده"),
        DriverLicNumber = FormValues.Required(values, "License", "شماره گواهینامه"),
        DateLic = FormValues.Date(values, "LicenseDate", "تاریخ صدور گواهینامه"),
        DateLicValidity = FormValues.Byte(values, "LicenseValidity", "اعتبار گواهینامه"),
        DamagePercentage = FormValues.Byte(values, "Damage", "درصد خسارت")
    });

    private static EntityRow ToRow(CarListItemResponse car) => new()
    {
        Id = car.Id,
        Status = car.DamagePercentage >= 70 ? "خسارت سنگین" : car.DamagePercentage >= 30 ? "نیازمند بررسی" : "ثبت‌شده",
        StatusTone = RmsUi.InjuryTone(car.DamagePercentage),
        Values = new()
        {
            ["Plate"] = car.PlateNumber,
            ["Car"] = car.CarName,
            ["Class"] = RmsUi.CarClass(car.CarClass),
            ["Year"] = car.ProductionYear.ToString().TranslateDigits(),
            ["Damage"] = $"{car.DamagePercentage.ToString().TranslateDigits()}٪"
        }
    };

    private static IReadOnlyDictionary<string, string> ToDraft(CarResponse car) => new Dictionary<string, string>
    {
        ["Plate"] = car.PlateNumber,
        ["Car"] = car.CarName,
        ["Class"] = Convert.ToByte(car.CarClass).ToString(),
        ["Year"] = car.ProductionYear.ToString(),
        ["Color"] = car.Color,
        ["DriverPhone"] = car.DriverPhone,
        ["License"] = car.DriverLicNumber,
        ["LicenseDate"] = car.DateLic.ToString("yyyy-MM-dd"),
        ["LicenseValidity"] = car.DateLicValidity.ToString(),
        ["Damage"] = car.DamagePercentage.ToString()
    };

    private string GetDraft(string key) => draft.GetValueOrDefault(key, string.Empty);
    private void SetDraft(string key, object? value) => draft[key] = value?.ToString() ?? string.Empty;
    private void ChangePlate(ChangeEventArgs eventArgs) => SetDraft("Plate", eventArgs.Value);
    private void ChangeCarName(ChangeEventArgs eventArgs) => SetDraft("Car", eventArgs.Value);
    private void ChangeClass(ChangeEventArgs eventArgs) => SetDraft("Class", eventArgs.Value);
    private void ChangeYear(ChangeEventArgs eventArgs) => SetDraft("Year", eventArgs.Value);
    private void ChangeColor(ChangeEventArgs eventArgs) => SetDraft("Color", eventArgs.Value);
    private void ChangeDriverPhone(ChangeEventArgs eventArgs) => SetDraft("DriverPhone", eventArgs.Value);
    private void ChangeLicense(ChangeEventArgs eventArgs) => SetDraft("License", eventArgs.Value);
    private DateTime LicenseDatePicker
    {
        get => licenseDatePicker;
        set
        {
            licenseDatePicker = value;
            draft["LicenseDate"] = DateOnly.FromDateTime(value).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        }
    }

    private void SyncLicenseDatePickerFromDraft()
    {
        if (DateOnly.TryParseExact(GetDraft("LicenseDate"), "yyyy-MM-dd", CultureInfo.InvariantCulture,
            DateTimeStyles.None, out var value))
        {
            licenseDatePicker = value.ToDateTime(TimeOnly.MinValue);
        }
    }

    private void OnLicenseDateChanged()
    {
        if (licenseDatePickerComponent is not null)
            LicenseDatePicker = licenseDatePickerComponent.SelectDate ?? DateTime.Today;
    }
    private void ChangeLicenseValidity(ChangeEventArgs eventArgs) => SetDraft("LicenseValidity", eventArgs.Value);
    private void ChangeDamage(ChangeEventArgs eventArgs) => SetDraft("Damage", eventArgs.Value);

    private static bool IsExpectedException(Exception exception) =>
        exception is ApiClientException or HttpRequestException or FormatException or InvalidOperationException or ArgumentException;

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ when !string.IsNullOrWhiteSpace(exception.Message) => exception.Message,
        _ => fallback
    };
}
