// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Forms;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.AccidentsLogging;

public partial class Images
{
    [Parameter]
    public Guid? AccidentId
    {
        get; set;
    }

    private const long MaxUploadBytes = 1_400_000;
    private readonly List<ImageResponse> images = [];
    private AccidentResponse? parentAccident;
    private bool isLoading = true;
    private string? pageError;
    private string? successMessage;

    private bool uploadOpen;
    private IBrowserFile? selectedFile;
    private bool isUploading;
    private string? uploadError;

    private bool deleteOpen;
    private bool deleteAll;
    private ImageResponse? deletingImage;
    private bool isDeleting;
    private string? deleteError;

    private ImageResponse? viewerImage;
    private int viewerIndex;

    private string PageTitleText => AccidentId.HasValue
        ? $"تصاویر حادثه ACC-{RmsUi.ShortId(AccidentId.Value)}"
        : "تصاویر حوادث";
    private string PageDescription => AccidentId.HasValue
        ? "مشاهده و ثبت تصاویر همین حادثه؛ شناسه حادثه به‌صورت خودکار اعمال می‌شود."
        : "تصاویر هر حادثه از صفحه اختصاصی همان حادثه مدیریت می‌شوند.";

    private bool CanList => AuthenticationState.HasPermission(UserSection.Images, UserAccessOperation.Report);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Images, UserAccessOperation.Create);
    private bool CanCreateHere => CanCreate && AccidentId.HasValue && parentAccident is not null;
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Images, UserAccessOperation.Delete);
    private bool CanListAccidents => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
    private bool CanListCars => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);

    /// <summary>راه والد را انتخاب می‌کند تا جستجوی حادثه محدود شود.</summary>
    private Task HandleAccidentSelectedAsync(Guid? accidentId)
    {
        if (accidentId.HasValue)
            Navigation.NavigateTo($"/accidents/{accidentId.Value}/images");
        return Task.CompletedTask;
    }

    /*
    private Task SelectRoadAsync(string value)
    {
        selectedRoad = value;
        filterRoadId = Guid.TryParse(value, out var roadId) ? roadId : null;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    /// <summary>ماه فیلتر حادثه را از تقویم فارسی دریافت می‌کند.</summary>
    private Task OnFilterMonthChanged()
    {
        filterMonth = filterMonthPickerComponent?.SelectDate ?? DateTime.Now;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    private Task SelectAccidentAsync(string value)
    {
        if (Guid.TryParse(value, out var accidentId))
            Navigation.NavigateTo($"/accidents/{accidentId}/images");
        return Task.CompletedTask;
    }

    private async Task<IReadOnlyList<LookupOption>> SearchAccidentsAsync(string term, CancellationToken token)
    {
        if (!filterRoadId.HasValue)
            return (await LookupApi.GetRoadsAsync(new LookupQuery { SearchTerm = term, Take = 20 }, token))
                .Select(road => new LookupOption(road.Id.ToString(), road.Name)).ToArray();
        return await AccidentFilterHelper.SearchAccidentsAsync(AccidentApi, filterRoadId, filterMonth, term, token);
    }
    //
        (await LookupApi.GetAccidentsAsync(new AccidentLookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(accident => new LookupOption(accident.Id.ToString(), $"{accident.RoadName} · {RmsUi.DateTime(accident.AccidentTimeUnix)}"))
            .ToArray();

    */

    protected override async Task OnParametersSetAsync()
    {
        images.Clear();
        parentAccident = null;
        pageError = null;

        if (!CanList || !AccidentId.HasValue)
        {
            isLoading = false;
            return;
        }

        isLoading = true;
        try
        {
            parentAccident = await AccidentApi.GetByIdAsync(AccidentId.Value);
            await LoadImagesCoreAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت اطلاعات حادثه و تصاویر آن با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadImagesAsync()
    {
        images.Clear();
        if (!AccidentId.HasValue)
        {
            isLoading = false;
            return;
        }

        isLoading = true;
        pageError = null;
        try
        {
            await LoadImagesCoreAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت تصاویر حادثه با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadImagesCoreAsync()
    {
        if (!AccidentId.HasValue)
            return;
        images.AddRange(await ImageApi.GetAllAsync(AccidentId.Value));
    }

    private void OpenViewer(ImageResponse image)
    {
        viewerIndex = images.FindIndex(item => item.Id == image.Id);
        viewerIndex = viewerIndex < 0 ? 0 : viewerIndex;
        viewerImage = images.Count == 0 ? null : images[viewerIndex];
    }

    private void CloseViewer() => viewerImage = null;

    private void PreviousViewerImage()
    {
        if (images.Count == 0)
            return;

        viewerIndex = (viewerIndex - 1 + images.Count) % images.Count;
        viewerImage = images[viewerIndex];
    }

    private void NextViewerImage()
    {
        if (images.Count == 0)
            return;

        viewerIndex = (viewerIndex + 1) % images.Count;
        viewerImage = images[viewerIndex];
    }

    private void OpenUpload()
    {
        if (!CanCreateHere)
            return;
        selectedFile = null;
        uploadError = null;
        uploadOpen = true;
    }

    private void CloseUpload()
    {
        if (!isUploading)
            uploadOpen = false;
    }

    private void SelectFile(InputFileChangeEventArgs args)
    {
        selectedFile = args.File;
        uploadError = selectedFile.Size > MaxUploadBytes ? "حجم تصویر نباید بیشتر از ۱٫۴ مگابایت باشد." : null;
    }

    private async Task UploadAsync()
    {
        uploadError = null;
        if (!AccidentId.HasValue)
        {
            uploadError = "بارگذاری تصویر باید از صفحه حادثه انجام شود.";
            return;
        }
        if (selectedFile is null)
        {
            uploadError = "یک تصویر انتخاب کنید.";
            return;
        }
        if (selectedFile.Size > MaxUploadBytes)
        {
            uploadError = "حجم تصویر نباید بیشتر از ۱٫۴ مگابایت باشد.";
            return;
        }

        isUploading = true;
        try
        {
            await using var stream = selectedFile.OpenReadStream(MaxUploadBytes);
            using var memory = new MemoryStream();
            await stream.CopyToAsync(memory);
            var base64 = $"data:{selectedFile.ContentType};base64,{Convert.ToBase64String(memory.ToArray())}";
            await ImageApi.CreateAsync(new CreateAccidentImageCommand
            {
                AccidentId = AccidentId.Value,
                Base64Image = base64
            });
            uploadOpen = false;
            successMessage = "تصویر با موفقیت برای این حادثه بارگذاری شد.";
            await LoadImagesAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException or IOException)
        {
            uploadError = ErrorMessage(exception, "بارگذاری تصویر با خطا مواجه شد.");
        }
        finally
        {
            isUploading = false;
        }
    }

    private void AskDelete(ImageResponse image)
    {
        deletingImage = image;
        deleteAll = false;
        deleteError = null;
        deleteOpen = true;
    }

    private void AskDeleteAll()
    {
        deletingImage = null;
        deleteAll = true;
        deleteError = null;
        deleteOpen = true;
    }

    private void CloseDelete()
    {
        if (!isDeleting)
            deleteOpen = false;
    }

    private async Task DeleteAsync()
    {
        isDeleting = true;
        deleteError = null;
        try
        {
            if (deleteAll && AccidentId.HasValue)
                await ImageApi.DeleteAllAsync(AccidentId.Value);
            else if (deletingImage is not null)
                await ImageApi.DeleteAsync(deletingImage.Id);
            else
                return;

            deleteOpen = false;
            successMessage = deleteAll ? "همه تصاویر حادثه حذف شدند." : "تصویر با موفقیت حذف شد.";
            await LoadImagesAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            deleteError = ErrorMessage(exception, "حذف تصویر با خطا مواجه شد.");
        }
        finally
        {
            isDeleting = false;
        }
    }

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        IOException => "خواندن فایل تصویر با خطا مواجه شد.",
        _ => fallback
    };
}
