// <auto-generated/>
using Microsoft.AspNetCore.Components;
using RMS.Client.Components;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.AccidentsLogging;

public partial class Passengers
{
    [Parameter]
    public Guid? CarId
    {
        get; set;
    }

    private static readonly EntityColumn[] scopedColumns =
    [
        new("NationalCode", "کد ملی"), new("Name", "نام و نام خانوادگی"), new("Role", "نقش"),
    new("Gender", "جنسیت"), new("Injury", "آسیب")
    ];

    private readonly List<EntityRow> rows = [];
    private readonly Dictionary<string, string> draft = new(StringComparer.OrdinalIgnoreCase);
    private EntityListPanel? listPanel;
    private CarResponse? parentCar;
    private EntityRow? editingRow;
    private EntityRow? deletingRow;
    private int totalCount;
    private bool isLoading = true;
    private bool modalOpen;
    private bool deleteModalOpen;
    private bool isLoadingEditor;
    private bool isMutating;
    private string? pageError;
    private string? mutationError;
    private string? deleteError;
    private string? successMessage;

    private IReadOnlyList<EntityColumn> Columns => scopedColumns;
    private string PageTitleText => parentCar is not null
        ? $"سرنشینان {parentCar.PlateNumber}"
        : CarId.HasValue ? "رانندگان و سرنشینان خودرو" : "رانندگان و سرنشینان";
    private string PageDescription => CarId.HasValue
        ? "ثبت و مدیریت افراد همین خودرو؛ شناسه خودرو به‌صورت خودکار اعمال می‌شود."
        : "فهرست همه رانندگان و سرنشینان؛ برای ثبت شخص از صفحه خودرو وارد شوید.";

    private bool CanList => AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.Report);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.Create);
    private bool CanCreateHere => CanCreate && CarId.HasValue && parentCar is not null;
    private bool CanUpdate => AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.View)
        && AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Passengers, UserAccessOperation.Delete);
    private bool CanListAccidents => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
    private bool CanListPeople => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);
    private string selectedAccident = string.Empty;


    /// <summary>راه والد را انتخاب می‌کند تا جستجوی حادثه محدود شود.</summary>
    /// <summary>ماه فیلتر حادثه را از تقویم فارسی دریافت می‌کند.</summary>
    /// <summary>شناسه حادثه خروجی AccidentWizard را برای جستجوی خودرو نگه می‌دارد.</summary>
    private Task HandleAccidentSelectedAsync(Guid? accidentId)
    {
        selectedAccident = accidentId?.ToString() ?? string.Empty;
        return Task.CompletedTask;
    }

    private Task SelectCarAsync(string value)
    {
        if (Guid.TryParse(value, out var carId))
            Navigation.NavigateTo($"/cars/{carId}/passengers");
        return Task.CompletedTask;
    }

    /*
        (await LookupApi.GetAccidentsAsync(new AccidentLookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(accident => new LookupOption(accident.Id.ToString(), $"{accident.RoadName} · {RmsUi.DateTime(accident.AccidentTimeUnix)}"))
            .ToArray();

    */

    private async Task<IReadOnlyList<LookupOption>> SearchCarsAsync(string term, CancellationToken token)
    {
        if (!Guid.TryParse(selectedAccident, out var accidentId))
            return [];

        return (await LookupApi.GetCarsAsync(new CarLookupQuery
        {
            AccidentId = accidentId,
            SearchTerm = term,
            Take = 20
        }, token))
            .Select(car => new LookupOption(car.Id.ToString(), $"{car.PlateNumber} · {car.CarName}"))
            .ToArray();
    }

    protected override async Task OnParametersSetAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }

        parentCar = null;
        pageError = null;
        if (CarId.HasValue)
        {
            try
            {
                parentCar = await CarApi.GetByIdAsync(CarId.Value);
            }
            catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
            {
                pageError = ErrorMessage(exception, "دریافت اطلاعات خودرو با خطا مواجه شد.");
                isLoading = false;
                rows.Clear();
                totalCount = 0;
                return;
            }
        }
        else
        {
            rows.Clear();
            totalCount = 0;
            isLoading = false;
            return;
        }
        await LoadAsync();
    }

    private async Task LoadAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(new EntityPageRequest(0, 20, string.Empty, CancellationToken.None));
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت رانندگان و سرنشینان از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadPageAsync(EntityPageRequest request)
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(request);
        }
        catch (OperationCanceledException) when (request.CancellationToken.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت رانندگان و سرنشینان از API با خطا مواجه شد.");
        }
        finally
        {
            if (!request.CancellationToken.IsCancellationRequested)
                isLoading = false;
        }
    }

    private async Task LoadPageCoreAsync(EntityPageRequest request)
    {
        if (!CarId.HasValue)
        {
            rows.Clear();
            totalCount = 0;
            return;
        }

        var result = await PassengerApi.GetAllAsync(new PassengerQueries
        {
            CarId = CarId,
            Skip = request.Skip,
            Take = request.Take,
            SearchTerm = request.SearchTerm
        }, request.CancellationToken);
        rows.Clear();
        rows.AddRange(result.Items.Select(ToRow));
        totalCount = result.TotalCount;
    }

    private void OpenCreate()
    {
        if (!CanCreateHere)
            return;
        editingRow = null;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = false;
        modalOpen = true;
    }

    private async Task OpenEditAsync(EntityRow row)
    {
        editingRow = row;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = true;
        modalOpen = true;
        try
        {
            foreach (var item in ToDraft(await PassengerApi.GetByIdAsync(row.Id)))
                draft[item.Key] = item.Value;
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "دریافت جزئیات شخص با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private void CloseModal()
    {
        if (!isMutating)
            modalOpen = false;
    }

    private async Task SaveAsync()
    {
        mutationError = null;
        isMutating = true;
        try
        {
            if (editingRow is null)
            {
                if (!CarId.HasValue)
                    throw new InvalidOperationException("ثبت راننده یا سرنشین باید از صفحه خودرو انجام شود.");
                await CreateAsync(CarId.Value, draft);
                successMessage = "راننده یا سرنشین با موفقیت برای این خودرو ثبت شد.";
            }
            else
            {
                await UpdateAsync(editingRow.Id, draft);
                successMessage = "اطلاعات شخص با موفقیت ویرایش شد.";
            }

            modalOpen = false;
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "ذخیره اطلاعات شخص با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private void AskDelete(EntityRow row)
    {
        deletingRow = row;
        deleteError = null;
        deleteModalOpen = true;
    }

    private void CloseDeleteModal()
    {
        if (!isMutating)
            deleteModalOpen = false;
    }

    private async Task ConfirmDeleteAsync()
    {
        if (deletingRow is null)
            return;
        deleteError = null;
        isMutating = true;
        try
        {
            await PassengerApi.DeleteAsync(deletingRow.Id);
            deleteModalOpen = false;
            successMessage = "راننده یا سرنشین با موفقیت حذف شد.";
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            deleteError = ErrorMessage(exception, "حذف شخص با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private Task CreateAsync(Guid carId, IReadOnlyDictionary<string, string> values) => PassengerApi.CreateAsync(new CreatePassengerCommand
    {
        FkCar = carId,
        NationalCode = FormValues.Required(values, "NationalCode", "کد ملی"),
        PassengerFullName = FormValues.Required(values, "Name", "نام و نام خانوادگی"),
        IsDriver = bool.Parse(FormValues.Required(values, "IsDriver", "نقش")),
        Gender = FormValues.Enum<GenderEnums>(values, "Gender", "جنسیت"),
        Age = FormValues.Byte(values, "Age", "سن"),
        InjuryPercentage = FormValues.Byte(values, "Injury", "درصد آسیب"),
        TypePersonDamage = FormValues.Enum<DamageTypePersonEnum>(values, "DamageType", "نوع آسیب"),
        DescriptionDamage = FormValues.Optional(values, "Description")
    });

    private Task UpdateAsync(Guid id, IReadOnlyDictionary<string, string> values) => PassengerApi.UpdateAsync(id, new UpdatePassengerCommand
    {
        Id = id,
        NationalCode = FormValues.Required(values, "NationalCode", "کد ملی"),
        PassengerFullName = FormValues.Required(values, "Name", "نام و نام خانوادگی"),
        IsDriver = bool.Parse(FormValues.Required(values, "IsDriver", "نقش")),
        Gender = FormValues.Enum<GenderEnums>(values, "Gender", "جنسیت"),
        Age = FormValues.Byte(values, "Age", "سن"),
        InjuryPercentage = FormValues.Byte(values, "Injury", "درصد آسیب"),
        TypePersonDamage = FormValues.Enum<DamageTypePersonEnum>(values, "DamageType", "نوع آسیب"),
        DescriptionDamage = FormValues.Optional(values, "Description")
    });

    private static EntityRow ToRow(PassengerListItemResponse passenger) => new()
    {
        Id = passenger.Id,
        Status = RmsUi.DamageType(passenger.DamageType),
        StatusTone = RmsUi.InjuryTone(passenger.InjuryPercentage),
        Values = new()
        {
            ["NationalCode"] = passenger.NationalCode,
            ["Name"] = passenger.FullName,
            ["Role"] = passenger.IsDriver ? "راننده" : "سرنشین",
            ["Car"] = passenger.CarPlate,
            ["Gender"] = RmsUi.Gender(passenger.Gender),
            ["Injury"] = $"{passenger.InjuryPercentage.ToString().TranslateDigits()}٪"
        }
    };

    private static IReadOnlyDictionary<string, string> ToDraft(PassengerResponse passenger) => new Dictionary<string, string>
    {
        ["NationalCode"] = passenger.NationalCode,
        ["Name"] = passenger.PassengerFullName,
        ["IsDriver"] = passenger.IsDriver ? "true" : "false",
        ["Gender"] = Convert.ToByte(passenger.Gender).ToString(),
        ["Age"] = passenger.Age.ToString(),
        ["Injury"] = passenger.InjuryPercentage.ToString(),
        ["DamageType"] = Convert.ToByte(passenger.TypePersonDamage).ToString(),
        ["Description"] = passenger.DescriptionDamage
    };

    private string GetDraft(string key) => draft.GetValueOrDefault(key, string.Empty);
    private void SetDraft(string key, object? value) => draft[key] = value?.ToString() ?? string.Empty;
    private void ChangeNationalCode(ChangeEventArgs eventArgs) => SetDraft("NationalCode", eventArgs.Value);
    private void ChangeName(ChangeEventArgs eventArgs) => SetDraft("Name", eventArgs.Value);
    private void ChangeRole(ChangeEventArgs eventArgs) => SetDraft("IsDriver", eventArgs.Value);
    private void ChangeGender(ChangeEventArgs eventArgs) => SetDraft("Gender", eventArgs.Value);
    private void ChangeAge(ChangeEventArgs eventArgs) => SetDraft("Age", eventArgs.Value);
    private void ChangeInjury(ChangeEventArgs eventArgs) => SetDraft("Injury", eventArgs.Value);
    private void ChangeDamageType(ChangeEventArgs eventArgs) => SetDraft("DamageType", eventArgs.Value);
    private void ChangeDescription(ChangeEventArgs eventArgs) => SetDraft("Description", eventArgs.Value);

    private static bool IsExpectedException(Exception exception) =>
        exception is ApiClientException or HttpRequestException or FormatException or InvalidOperationException or ArgumentException;

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ when !string.IsNullOrWhiteSpace(exception.Message) => exception.Message,
        _ => fallback
    };
}
