// <auto-generated/>
using Microsoft.AspNetCore.Components;
using RMS.Client.Components;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.AccidentsLogging;

public partial class People
{
    [Parameter]
    public Guid? AccidentId
    {
        get; set;
    }

    private static readonly EntityColumn[] scopedColumns =
    [
        new("NationalCode", "کد ملی"), new("Name", "نام و نام خانوادگی"), new("Gender", "جنسیت"),
    new("Age", "سن"), new("Injury", "آسیب")
    ];

    private readonly List<EntityRow> rows = [];
    private readonly Dictionary<string, string> draft = new(StringComparer.OrdinalIgnoreCase);
    private EntityListPanel? listPanel;
    private AccidentResponse? parentAccident;
    private EntityRow? editingRow;
    private EntityRow? deletingRow;
    private int totalCount;
    private bool isLoading = true;
    private bool modalOpen;
    private bool deleteModalOpen;
    private bool isLoadingEditor;
    private bool isMutating;
    private string? pageError;
    private string? mutationError;
    private string? deleteError;
    private string? successMessage;

    private IReadOnlyList<EntityColumn> Columns => scopedColumns;
    private string PageTitleText => AccidentId.HasValue ? $"افراد حادثه ACC-{RmsUi.ShortId(AccidentId.Value)}" : "انتخاب حادثه برای افراد";
    private string PageDescription => AccidentId.HasValue
        ? "ثبت عابر و سایر افراد همین حادثه؛ شناسه حادثه به‌صورت خودکار اعمال می‌شود."
        : "برای مشاهده یا ثبت فرد، ابتدا از فهرست حوادث یک حادثه را انتخاب کنید.";

    private bool CanList => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Create);
    private bool CanCreateHere => CanCreate && AccidentId.HasValue && parentAccident is not null;
    private bool CanUpdate => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.View)
        && AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Delete);
    private bool CanListAccidents => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
    private bool CanListCars => AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);

    /// <summary>راه والد را انتخاب می‌کند تا جستجوی حادثه محدود شود.</summary>
    private Task HandleAccidentSelectedAsync(Guid? accidentId)
    {
        if (accidentId.HasValue)
            Navigation.NavigateTo($"/accidents/{accidentId.Value}/people");
        return Task.CompletedTask;
    }

    /*
    private Task SelectRoadAsync(string value)
    {
        selectedRoad = value;
        filterRoadId = Guid.TryParse(value, out var roadId) ? roadId : null;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    /// <summary>ماه فیلتر حادثه را از تقویم فارسی دریافت می‌کند.</summary>
    private Task OnFilterMonthChanged()
    {
        filterMonth = filterMonthPickerComponent?.SelectDate ?? DateTime.Now;
        selectedAccident = string.Empty;
        return Task.CompletedTask;
    }

    private Task SelectAccidentAsync(string value)
    {
        if (Guid.TryParse(value, out var accidentId))
            Navigation.NavigateTo($"/accidents/{accidentId}/people");
        return Task.CompletedTask;
    }

    private async Task<IReadOnlyList<LookupOption>> SearchAccidentsAsync(string term, CancellationToken token)
    {
        if (!filterRoadId.HasValue)
            return (await LookupApi.GetRoadsAsync(new LookupQuery { SearchTerm = term, Take = 20 }, token))
                .Select(road => new LookupOption(road.Id.ToString(), road.Name)).ToArray();
        return await AccidentFilterHelper.SearchAccidentsAsync(AccidentApi, filterRoadId, filterMonth, term, token);
    }
    //
        (await LookupApi.GetAccidentsAsync(new AccidentLookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(accident => new LookupOption(accident.Id.ToString(), $"{accident.RoadName} · {RmsUi.DateTime(accident.AccidentTimeUnix)}"))
            .ToArray();

    */

    protected override async Task OnParametersSetAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }

        parentAccident = null;
        pageError = null;
        if (AccidentId.HasValue)
        {
            try
            {
                parentAccident = await AccidentApi.GetByIdAsync(AccidentId.Value);
            }
            catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
            {
                pageError = ErrorMessage(exception, "دریافت اطلاعات حادثه با خطا مواجه شد.");
                isLoading = false;
                rows.Clear();
                totalCount = 0;
                return;
            }
        }
        else
        {
            rows.Clear();
            totalCount = 0;
            isLoading = false;
            return;
        }

        await LoadAsync();
    }

    private async Task LoadAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(new EntityPageRequest(0, 20, string.Empty, CancellationToken.None));
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت عابر از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadPageAsync(EntityPageRequest request)
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadPageCoreAsync(request);
        }
        catch (OperationCanceledException) when (request.CancellationToken.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت عابر از API با خطا مواجه شد.");
        }
        finally
        {
            if (!request.CancellationToken.IsCancellationRequested)
                isLoading = false;
        }
    }

    private async Task LoadPageCoreAsync(EntityPageRequest request)
    {
        if (!AccidentId.HasValue)
        {
            rows.Clear();
            totalCount = 0;
            return;
        }

        var result = await PeopleApi.GetAllAsync(new PeopleQueries
        {
            AccidentId = AccidentId.Value,
            Skip = request.Skip,
            Take = request.Take,
            SearchTerm = request.SearchTerm
        }, request.CancellationToken);
        rows.Clear();
        rows.AddRange(result.Items.Select(ToRow));
        totalCount = result.TotalCount;
    }

    private void OpenCreate()
    {
        if (!CanCreateHere)
            return;
        editingRow = null;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = false;
        modalOpen = true;
    }

    private async Task OpenEditAsync(EntityRow row)
    {
        editingRow = row;
        draft.Clear();
        mutationError = null;
        isLoadingEditor = true;
        modalOpen = true;
        try
        {
            foreach (var item in ToDraft(await PeopleApi.GetByIdAsync(row.Id)))
                draft[item.Key] = item.Value;
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "دریافت جزئیات فرد با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private void CloseModal()
    {
        if (!isMutating)
            modalOpen = false;
    }

    private async Task SaveAsync()
    {
        mutationError = null;
        isMutating = true;
        try
        {
            if (editingRow is null)
            {
                if (!AccidentId.HasValue)
                    throw new InvalidOperationException("ثبت فرد باید از صفحه حادثه انجام شود.");
                await CreateAsync(AccidentId.Value, draft);
                successMessage = "فرد با موفقیت برای این حادثه ثبت شد.";
            }
            else
            {
                await UpdateAsync(editingRow.Id, draft);
                successMessage = "اطلاعات فرد با موفقیت ویرایش شد.";
            }

            modalOpen = false;
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            mutationError = ErrorMessage(exception, "ذخیره اطلاعات فرد با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private void AskDelete(EntityRow row)
    {
        deletingRow = row;
        deleteError = null;
        deleteModalOpen = true;
    }

    private void CloseDeleteModal()
    {
        if (!isMutating)
            deleteModalOpen = false;
    }

    private async Task ConfirmDeleteAsync()
    {
        if (deletingRow is null)
            return;
        deleteError = null;
        isMutating = true;
        try
        {
            await PeopleApi.DeleteAsync(deletingRow.Id);
            deleteModalOpen = false;
            successMessage = "فرد با موفقیت حذف شد.";
            if (listPanel is not null)
                await listPanel.ReloadAsync();
            else
                await LoadAsync();
        }
        catch (Exception exception) when (IsExpectedException(exception))
        {
            deleteError = ErrorMessage(exception, "حذف فرد با خطا مواجه شد.");
        }
        finally
        {
            isMutating = false;
        }
    }

    private Task CreateAsync(Guid accidentId, IReadOnlyDictionary<string, string> values) => PeopleApi.CreateAsync(new CreatePeopleCommand
    {
        FkAccident = accidentId,
        NationalCode = FormValues.Required(values, "NationalCode", "کد ملی"),
        PassengerFullName = FormValues.Required(values, "Name", "نام و نام خانوادگی"),
        Gender = FormValues.Enum<GenderEnums>(values, "Gender", "جنسیت"),
        Age = FormValues.Byte(values, "Age", "سن"),
        InjuryPercentage = FormValues.Byte(values, "Injury", "درصد آسیب"),
        TypePersonDamage = FormValues.Enum<DamageTypePersonEnum>(values, "DamageType", "نوع آسیب"),
        DescriptionDamage = FormValues.Optional(values, "Description")
    });

    private Task UpdateAsync(Guid id, IReadOnlyDictionary<string, string> values) => PeopleApi.UpdateAsync(id, new UpdatePeopleCommand
    {
        Id = id,
        NationalCode = FormValues.Required(values, "NationalCode", "کد ملی"),
        PassengerFullName = FormValues.Required(values, "Name", "نام و نام خانوادگی"),
        Gender = FormValues.Enum<GenderEnums>(values, "Gender", "جنسیت"),
        Age = FormValues.Byte(values, "Age", "سن"),
        InjuryPercentage = FormValues.Byte(values, "Injury", "درصد آسیب"),
        TypePersonDamage = FormValues.Enum<DamageTypePersonEnum>(values, "DamageType", "نوع آسیب"),
        DescriptionDamage = FormValues.Optional(values, "Description")
    });

    private static EntityRow ToRow(PeopleListItemResponse person) => new()
    {
        Id = person.Id,
        Status = RmsUi.DamageType(person.DamageType),
        StatusTone = RmsUi.InjuryTone(person.InjuryPercentage),
        Values = new()
        {
            ["NationalCode"] = person.NationalCode,
            ["Name"] = person.FullName,
            ["Gender"] = RmsUi.Gender(person.Gender),
            ["Age"] = person.Age.ToString().TranslateDigits(),
            ["Accident"] = person.AccidentCode,
            ["Injury"] = $"{person.InjuryPercentage.ToString().TranslateDigits()}٪"
        }
    };

    private static IReadOnlyDictionary<string, string> ToDraft(PeopleResponse person) => new Dictionary<string, string>
    {
        ["NationalCode"] = person.NationalCode,
        ["Name"] = person.PassengerFullName,
        ["Gender"] = Convert.ToByte(person.Gender).ToString(),
        ["Age"] = person.Age.ToString(),
        ["Injury"] = person.InjuryPercentage.ToString(),
        ["DamageType"] = Convert.ToByte(person.TypePersonDamage).ToString(),
        ["Description"] = person.DescriptionDamage
    };

    private string GetDraft(string key) => draft.GetValueOrDefault(key, string.Empty);
    private void SetDraft(string key, object? value) => draft[key] = value?.ToString() ?? string.Empty;
    private void ChangeNationalCode(ChangeEventArgs eventArgs) => SetDraft("NationalCode", eventArgs.Value);
    private void ChangeName(ChangeEventArgs eventArgs) => SetDraft("Name", eventArgs.Value);
    private void ChangeGender(ChangeEventArgs eventArgs) => SetDraft("Gender", eventArgs.Value);
    private void ChangeAge(ChangeEventArgs eventArgs) => SetDraft("Age", eventArgs.Value);
    private void ChangeInjury(ChangeEventArgs eventArgs) => SetDraft("Injury", eventArgs.Value);
    private void ChangeDamageType(ChangeEventArgs eventArgs) => SetDraft("DamageType", eventArgs.Value);
    private void ChangeDescription(ChangeEventArgs eventArgs) => SetDraft("Description", eventArgs.Value);

    private static bool IsExpectedException(Exception exception) =>
        exception is ApiClientException or HttpRequestException or FormatException or InvalidOperationException or ArgumentException;

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ when !string.IsNullOrWhiteSpace(exception.Message) => exception.Message,
        _ => fallback
    };
}
