// <auto-generated/>
using Microsoft.JSInterop;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages;

public partial class Home
{
    private DashboardOverviewResponse? dashboard;
    private bool isLoading = true;
    private bool chartsPending;
    private bool chartsRendered;
    private string? pageError;

    private string TodayLabel => DateTime.Now.ToString("yyyy/MM/dd").TranslateDigits();
    private bool CanAccess => AuthenticationState.HasPermission(UserSection.Reports, UserAccessOperation.Report);
    private List<RecentAccidentItem> RecentAccidents => (dashboard?.RecentAccidents ?? [])
        .Select(item =>
        {
            var local = DateTimeOffset.FromUnixTimeSeconds(item.AccidentTimeUnix).ToLocalTime();
            var tone = RmsUi.InjuryTone(item.InjuryPercentage);
            return new RecentAccidentItem(
                $"{RmsUi.AccidentType(item.AccidentType)} · ACC-{RmsUi.ShortId(item.Id)}",
                item.RoadName,
                local.ToString("HH:mm").TranslateDigits(), local.ToString("yyyy/MM/dd").TranslateDigits(),
                item.InjuryPercentage >= 70 ? "شدید" : item.InjuryPercentage >= 30 ? "متوسط" : "کم", tone);
        }).ToList();

    private List<ConditionItem> RoadConditions
    {
        get
        {
            var conditions = dashboard?.RoadConditions ?? [];
            var accidentCount = dashboard?.AccidentCount ?? 0;
            if (accidentCount == 0)
                return [];
            var tones = new[] { "primary", "cyan", "warning", "danger" };
            return conditions.Select((item, index) => new ConditionItem(
                    RmsUi.RoadCondition((RoadConditionEnums)item.Key), item.Count,
                    (int)Math.Round(item.Count * 100d / accidentCount), tones[index % tones.Length]))
                .ToList();
        }
    }

    protected override async Task OnInitializedAsync()
    {
        if (!CanAccess)
        {
            isLoading = false;
            return;
        }

        try
        {
            var endTime = DateTimeOffset.UtcNow.AddSeconds(1);
            dashboard = await AnalyticsApi.GetDashboardAsync(new DashboardQuery
            {
                StartTime = endTime.AddMonths(-12).ToUnixTimeSeconds(),
                EndTime = endTime.ToUnixTimeSeconds(),
                Months = 12,
                RecentCount = 4
            });
            chartsPending = true;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.";
        }
        finally
        {
            isLoading = false;
        }
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!chartsPending)
            return;
        chartsPending = false;
        await JS.InvokeVoidAsync("rmsInterop.renderDashboardCharts", BuildChartData());
        chartsRendered = true;
    }

    private DashboardChartData BuildChartData()
    {
        var trends = dashboard?.MonthlyTrend ?? [];
        var causes = dashboard?.Causes.Take(6).ToArray() ?? [];
        return new DashboardChartData(
            trends.Select(item => DateTimeOffset.FromUnixTimeSeconds(item.PeriodStartUnix).ToLocalTime().ToString("yyyy/MM").TranslateDigits()).ToArray(),
            trends.Select(item => item.AccidentCount).ToArray(),
            causes.Select(item => RmsUi.AccidentCause((AccidentCauseEnums)item.Key)).ToArray(),
            causes.Select(item => item.Count).ToArray());
    }

    private static string Persian(int value) => value.ToString("N0").TranslateDigits();

    public async ValueTask DisposeAsync()
    {
        if (chartsRendered)
            await JS.InvokeVoidAsync("rmsInterop.destroyCharts");
    }

    private sealed record RecentAccidentItem(string Title, string Location, string Time, string Date, string Severity, string Tone);
    private sealed record ConditionItem(string Name, int Count, int Percent, string Tone);
    private sealed record DashboardChartData(string[] TrendLabels, int[] TrendValues, string[] CauseLabels, int[] CauseValues);
}
