// <auto-generated/>
using Microsoft.AspNetCore.Components;
using RMS.Client.Services;
using RMS.Shared.Contracts.Authentication;

namespace RMS.Client.Pages;

public partial class Login
{
    private readonly LoginRequest model = new();
    private bool showPassword;
    private bool rememberMe = true;
    private bool isSubmitting;
    private string? errorMessage;

    [SupplyParameterFromQuery(Name = "returnUrl")]
    public string? ReturnUrl
    {
        get; set;
    }

    protected override async Task OnInitializedAsync()
    {
        if ((await AuthenticationState.GetAuthenticationStateAsync()).User.Identity?.IsAuthenticated == true)
            Navigation.NavigateTo(GetSafeReturnUrl(), replace: true);
    }

    private void TogglePassword() => showPassword = !showPassword;

    private async Task HandleLoginAsync()
    {
        isSubmitting = true;
        errorMessage = null;
        try
        {
            await Authentication.LoginAsync(model, rememberMe);
            Navigation.NavigateTo(GetSafeReturnUrl(), replace: true);
        }
        catch (ApiClientException exception)
        {
            errorMessage = exception.Message;
        }
        catch (HttpRequestException)
        {
            errorMessage = "ارتباط با سرویس ورود برقرار نشد. از اجرا بودن RMS.Api مطمئن شوید.";
        }
        finally
        {
            isSubmitting = false;
        }
    }

    private string GetSafeReturnUrl() =>
        !string.IsNullOrWhiteSpace(ReturnUrl) && ReturnUrl.StartsWith('/') && !ReturnUrl.StartsWith("//")
            ? ReturnUrl
            : "/";
}
