// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.JSInterop;

namespace RMS.Client.Components;

public partial class AppModal
{
    [Parameter]
    public bool IsOpen
    {
        get; set;
    }
    [Parameter]
    public bool Large
    {
        get; set;
    }
    [Parameter] public string Title { get; set; } = string.Empty;
    [Parameter]
    public string? Subtitle
    {
        get; set;
    }
    [Parameter] public string Icon { get; set; } = "bi-plus-lg";
    [Parameter]
    public EventCallback OnClose
    {
        get; set;
    }
    [Parameter]
    public RenderFragment? ChildContent
    {
        get; set;
    }
    [Parameter]
    public RenderFragment? Footer
    {
        get; set;
    }

    private Task RequestClose() => OnClose.InvokeAsync();
    private Task HandleKeyDown(KeyboardEventArgs args) => args.Key == "Escape" ? RequestClose() : Task.CompletedTask;
}
