// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using RMS.Client.Models;
using RMS.Client.Services;

namespace RMS.Client.Components;

public partial class AsyncLookup
{
    [Parameter] public string Value { get; set; } = string.Empty;
    [Parameter]
    public EventCallback<string> ValueChanged
    {
        get; set;
    }
    [Parameter, EditorRequired] public Func<string, CancellationToken, Task<IReadOnlyList<LookupOption>>> SearchAsync { get; set; } = null!;
    [Parameter] public string Placeholder { get; set; } = "برای جست‌وجو تایپ کنید...";
    [Parameter]
    public bool Required
    {
        get; set;
    }
    [Parameter]
    public bool Disabled
    {
        get; set;
    }

    private readonly List<LookupOption> results = [];
    private CancellationTokenSource? searchCancellation;
    private string displayText = string.Empty;
    private string loadedValue = string.Empty;
    private bool isLoading;
    private bool showResults;
    private string? searchError;

    protected override async Task OnParametersSetAsync()
    {
        if (Value == loadedValue)
            return;

        loadedValue = Value;
        if (string.IsNullOrWhiteSpace(Value))
        {
            displayText = string.Empty;
            return;
        }

        await ResolveSelectedLabelAsync(Value);
    }

    private async Task OnFocusAsync()
    {
        showResults = true;
        if (results.Count == 0)
            await SearchCoreAsync(displayText, null);
    }

    private async Task OnInputAsync(ChangeEventArgs eventArgs)
    {
        displayText = eventArgs.Value?.ToString() ?? string.Empty;
        showResults = true;
        if (!string.IsNullOrWhiteSpace(Value))
        {
            loadedValue = string.Empty;
            await ValueChanged.InvokeAsync(string.Empty);
        }
        await SearchCoreAsync(displayText, TimeSpan.FromMilliseconds(300));
    }

    private async Task SearchCoreAsync(string term, TimeSpan? delay)
    {
        searchCancellation?.Cancel();
        searchCancellation?.Dispose();
        searchCancellation = new CancellationTokenSource();
        var token = searchCancellation.Token;
        try
        {
            if (delay.HasValue)
                await Task.Delay(delay.Value, token);
            isLoading = true;
            searchError = null;
            await InvokeAsync(StateHasChanged);
            var found = await SearchAsync(term.Trim(), token);
            results.Clear();
            results.AddRange(found);
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            results.Clear();
            searchError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با API برقرار نشد.";
        }
        finally
        {
            if (!token.IsCancellationRequested)
            {
                isLoading = false;
                await InvokeAsync(StateHasChanged);
            }
        }
    }

    private async Task ResolveSelectedLabelAsync(string value)
    {
        try
        {
            var found = await SearchAsync(value, CancellationToken.None);
            var selected = found.FirstOrDefault(option => option.Value == value);
            displayText = selected?.Label ?? value;
            results.Clear();
            results.AddRange(found);
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            displayText = value;
        }
    }

    private async Task SelectAsync(LookupOption option)
    {
        displayText = option.Label;
        loadedValue = option.Value;
        showResults = false;
        await ValueChanged.InvokeAsync(option.Value);
    }

    private async Task ClearAsync()
    {
        displayText = string.Empty;
        loadedValue = string.Empty;
        showResults = true;
        await ValueChanged.InvokeAsync(string.Empty);
        await SearchCoreAsync(string.Empty, null);
    }

    public void Dispose()
    {
        searchCancellation?.Cancel();
        searchCancellation?.Dispose();
    }
}
