// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using RMS.Client.Models;

namespace RMS.Client.Components;

public partial class EntityListPanel
{
    [Parameter, EditorRequired] public IReadOnlyList<EntityColumn> Columns { get; set; } = [];
    [Parameter, EditorRequired] public IReadOnlyList<EntityRow> Rows { get; set; } = [];
    [Parameter]
    public int TotalCount
    {
        get; set;
    }
    [Parameter] public int PageSize { get; set; } = 20;
    [Parameter]
    public bool IsLoading
    {
        get; set;
    }
    [Parameter] public string SearchPlaceholder { get; set; } = "جست‌وجو...";
    [Parameter]
    public string? ErrorMessage
    {
        get; set;
    }
    [Parameter]
    public string? SuccessMessage
    {
        get; set;
    }
    [Parameter]
    public RenderFragment? ToolbarContent
    {
        get; set;
    }
    [Parameter]
    public RenderFragment<EntityRow>? RowActions
    {
        get; set;
    }
    [Parameter]
    public EventCallback<EntityPageRequest> QueryChanged
    {
        get; set;
    }

    private string searchTerm = string.Empty;
    private int currentPage;
    private CancellationTokenSource? queryCancellation;

    private int PageCount => Math.Max(1, (int)Math.Ceiling(TotalCount / (double)Math.Max(1, PageSize)));

    protected override void OnParametersSet()
    {
        if (currentPage >= PageCount)
            currentPage = Math.Max(0, PageCount - 1);
    }

    public Task ReloadAsync() => RequestServerPageAsync();

    private async Task OnSearchInputAsync(ChangeEventArgs eventArgs)
    {
        searchTerm = eventArgs.Value?.ToString() ?? string.Empty;
        currentPage = 0;
        await RequestServerPageAsync(TimeSpan.FromMilliseconds(350));
    }

    private async Task PreviousPageAsync()
    {
        currentPage = Math.Max(0, currentPage - 1);
        await RequestServerPageAsync();
    }

    private async Task NextPageAsync()
    {
        currentPage = Math.Min(PageCount - 1, currentPage + 1);
        await RequestServerPageAsync();
    }

    private async Task RequestServerPageAsync(TimeSpan? debounce = null)
    {
        if (!QueryChanged.HasDelegate)
            return;

        queryCancellation?.Cancel();
        queryCancellation?.Dispose();
        queryCancellation = new CancellationTokenSource();
        var token = queryCancellation.Token;
        try
        {
            if (debounce.HasValue)
                await Task.Delay(debounce.Value, token);
            await QueryChanged.InvokeAsync(new EntityPageRequest(
                currentPage * Math.Max(1, PageSize),
                Math.Max(1, PageSize),
                searchTerm.Trim(),
                token));
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
    }

    private static string GetValue(EntityRow row, string key) => row.Values.GetValueOrDefault(key, "—");
    private static string ToPersian(int value) => value.ToString().TranslateDigits();

    public void Dispose()
    {
        queryCancellation?.Cancel();
        queryCancellation?.Dispose();
    }
}
