// <auto-generated/>
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using RMS.Shared.Enums;

namespace RMS.Client.Components;

public partial class NavMenu
{
    [Parameter]
    public EventCallback OnNavigate
    {
        get; set;
    }
    [Parameter]
    public EventCallback OnLogout
    {
        get; set;
    }

    private bool CanAccess(UserSection section) =>
        AuthenticationState.HasPermission(section, UserAccessOperation.View) ||
        AuthenticationState.HasPermission(section, UserAccessOperation.Report) ||
        AuthenticationState.HasPermission(section, UserAccessOperation.Create) ||
        AuthenticationState.HasPermission(section, UserAccessOperation.Update) ||
        AuthenticationState.HasPermission(section, UserAccessOperation.Delete);

    private bool HasReportAccess(UserSection section) =>
        AuthenticationState.HasPermission(UserSection.Reports, UserAccessOperation.Report) &&
        AuthenticationState.HasPermission(section, UserAccessOperation.Report);

    private bool? accidentsMenuExpanded;

    private bool IsAccidentsMenuOpen => accidentsMenuExpanded ?? IsAccidentsRoute;

    private bool IsAccidentsRoute =>
        Navigation.Uri.Contains("/accidents", StringComparison.OrdinalIgnoreCase) ||
        Navigation.Uri.Contains("/cars", StringComparison.OrdinalIgnoreCase) ||
        Navigation.Uri.Contains("/passengers", StringComparison.OrdinalIgnoreCase) ||
        Navigation.Uri.Contains("/people", StringComparison.OrdinalIgnoreCase) ||
        Navigation.Uri.Contains("/images", StringComparison.OrdinalIgnoreCase);

    private void ToggleAccidentsMenu() => accidentsMenuExpanded = !IsAccidentsMenuOpen;

    private Task HandleNavigate() => OnNavigate.InvokeAsync();

    private async Task HandleLogout()
    {
        await OnNavigate.InvokeAsync();
        await OnLogout.InvokeAsync();
    }
}
