// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace RMS.Client.Components;

public partial class PageHeader
{
    [Parameter, EditorRequired] public string Title { get; set; } = string.Empty;
    [Parameter] public string Eyebrow { get; set; } = "سامانه مدیریت راه";
    [Parameter]
    public string? Description
    {
        get; set;
    }
    [Parameter]
    public RenderFragment? Actions
    {
        get; set;
    }
}
