// <auto-generated/>
namespace RMS.Client.Components;

public partial class RedirectToLogin
{
    protected override void OnInitialized()
    {
        var relativeUrl = Navigation.ToBaseRelativePath(Navigation.Uri);
        var returnUrl = string.IsNullOrWhiteSpace(relativeUrl) ? "/" : $"/{relativeUrl}";
        Navigation.NavigateTo($"/login?returnUrl={Uri.EscapeDataString(returnUrl)}", replace: true);
    }
}
