// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RMS.Infrastructure.Persistence.EF.Core;

#nullable disable

namespace RMS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RmsDbContext))]
    partial class RmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RMS.Domain.Entities.AccidentEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("AccidentCause")
                        .HasColumnType("tinyint");

                    b.Property<long>("AccidentTimeUnix")
                        .HasColumnType("bigint");

                    b.Property<byte>("AccidentType")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("FkIdRoad")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<byte>("LightingCondition")
                        .HasColumnType("tinyint");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte>("RoadCondition")
                        .HasColumnType("tinyint");

                    b.Property<byte>("TrafficSignCondition")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Weather")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AccidentTimeUnix")
                        .HasDatabaseName("IX_Accident_AccidentTimeUnix");

                    b.HasIndex("FkIdRoad");

                    b.ToTable("AccidentDs", t =>
                        {
                            t.HasCheckConstraint("CK_Accident_Cause", "[AccidentCause] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)");

                            t.HasCheckConstraint("CK_Accident_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Accident_LightingCondition", "[LightingCondition] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Accident_Longitude", "[Longitude] BETWEEN -180 AND 180");

                            t.HasCheckConstraint("CK_Accident_RoadCondition", "[RoadCondition] IN (0, 1, 2, 3, 4, 5, 6, 7)");

                            t.HasCheckConstraint("CK_Accident_RoadId_NotEmpty", "[FkIdRoad] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Accident_Time", "[AccidentTimeUnix] BETWEEN CAST(946684800 AS bigint) AND CAST(4102444800 AS bigint)");

                            t.HasCheckConstraint("CK_Accident_TrafficSignCondition", "[TrafficSignCondition] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Accident_Type", "[AccidentType] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)");

                            t.HasCheckConstraint("CK_Accident_Weather", "[Weather] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.CarEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CarClass")
                        .HasColumnType("tinyint");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("DamagePercentage")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly>("DateLic")
                        .HasColumnType("date");

                    b.Property<byte>("DateLicValidity")
                        .HasColumnType("tinyint");

                    b.Property<string>("DriverLicNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DriverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("FkAccident")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkAccident");

                    b.HasIndex("PlateNumber", "FkAccident")
                        .IsUnique()
                        .HasDatabaseName("UX_Car_PlateNumber_AccidentId");

                    b.ToTable("CarDs", t =>
                        {
                            t.HasCheckConstraint("CK_Car_AccidentId_NotEmpty", "[FkAccident] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Car_Class", "[CarClass] IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39)");

                            t.HasCheckConstraint("CK_Car_DamagePercentage", "[DamagePercentage] BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Car_LicenseDate", "[DateLic] BETWEEN '20200101' AND '21001231'");

                            t.HasCheckConstraint("CK_Car_LicenseValidity", "[DateLicValidity] BETWEEN 0 AND 20");

                            t.HasCheckConstraint("CK_Car_Name_NotBlank", "LEN(LTRIM(RTRIM([CarName]))) > 0");

                            t.HasCheckConstraint("CK_Car_PlateNumber_NotBlank", "LEN(LTRIM(RTRIM([PlateNumber]))) > 0");

                            t.HasCheckConstraint("CK_Car_ProductionYear", "[ProductionYear] BETWEEN 1300 AND 2200");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.ImageEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkAccident")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FkAccident");

                    b.ToTable("ImageDs");
                });

            modelBuilder.Entity("RMS.Domain.Entities.PassengerEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("DescriptionDamage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("FkCar")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InjuryPercentage")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsDriver")
                        .HasColumnType("bit");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PassengerFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TypePersonDamage")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("NationalCode", "FkCar")
                        .IsUnique()
                        .HasDatabaseName("UX_Passenger_NationalCode_CarId");

                    b.HasIndex(new[] { "FkCar" }, "UX_Passenger_OneDriverPerCar")
                        .IsUnique()
                        .HasFilter("[IsDriver] = 1");

                    b.ToTable("PassengerDs", t =>
                        {
                            t.HasCheckConstraint("CK_Passenger_Age", "[Age] BETWEEN 1 AND 150");

                            t.HasCheckConstraint("CK_Passenger_CarId_NotEmpty", "[FkCar] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_Passenger_DamageType", "[TypePersonDamage] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Passenger_FatalInjury", "[TypePersonDamage] <> 5 OR [InjuryPercentage] = 100");

                            t.HasCheckConstraint("CK_Passenger_Gender", "[Gender] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_Passenger_InjuryPercentage", "[InjuryPercentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_Passenger_NationalCode_NotBlank", "LEN(LTRIM(RTRIM([NationalCode]))) > 0");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.PeopleEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint");

                    b.Property<string>("DescriptionDamage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("FkAccident")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<byte>("InjuryPercentage")
                        .HasColumnType("tinyint");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PassengerFullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("TypePersonDamage")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FkAccident");

                    b.HasIndex("NationalCode", "FkAccident")
                        .IsUnique()
                        .HasDatabaseName("UX_People_NationalCode_AccidentId");

                    b.ToTable("PeopleDs", t =>
                        {
                            t.HasCheckConstraint("CK_People_AccidentId_NotEmpty", "[FkAccident] <> '00000000-0000-0000-0000-000000000000'");

                            t.HasCheckConstraint("CK_People_Age", "[Age] BETWEEN 1 AND 150");

                            t.HasCheckConstraint("CK_People_DamageType", "[TypePersonDamage] IN (0, 1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_People_FatalInjury", "[TypePersonDamage] <> 5 OR [InjuryPercentage] = 100");

                            t.HasCheckConstraint("CK_People_FullName_NotBlank", "LEN(LTRIM(RTRIM([PassengerFullName]))) > 0");

                            t.HasCheckConstraint("CK_People_Gender", "[Gender] IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_People_InjuryPercentage", "[InjuryPercentage] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_People_NationalCode_NotBlank", "LEN(LTRIM(RTRIM([NationalCode]))) > 0");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.RoadsEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Geometry>("Boundary")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<Point>("Centroid")
                        .HasColumnType("geography");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Road_Name");

                    b.ToTable("RoadsDs", t =>
                        {
                            t.HasCheckConstraint("CK_Road_Boundary_NotEmpty", "[Boundary].STIsEmpty() = 0");

                            t.HasCheckConstraint("CK_Road_Boundary_Srid", "[Boundary].STSrid = 4326");

                            t.HasCheckConstraint("CK_Road_Boundary_Type", "[Boundary].STGeometryType() IN ('LineString', 'MultiLineString', 'Polygon', 'MultiPolygon')");

                            t.HasCheckConstraint("CK_Road_Boundary_Valid", "[Boundary].STIsValid() = 1");

                            t.HasCheckConstraint("CK_Road_Centroid", "[Centroid] IS NULL OR ([Centroid].STSrid = 4326 AND [Centroid].STIsEmpty() = 0 AND [Centroid].STGeometryType() = 'Point')");

                            t.HasCheckConstraint("CK_Road_Centroid_InsideBoundary", "[Centroid] IS NULL OR [Boundary].STIntersects([Centroid]) = 1");

                            t.HasCheckConstraint("CK_Road_Name_NotBlank", "LEN(LTRIM(RTRIM([Name]))) > 0");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.UserEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("MobileNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_User_MobileNumber");

                    b.ToTable("UserDs", t =>
                        {
                            t.HasCheckConstraint("CK_User_FirstName_NotBlank", "LEN(LTRIM(RTRIM([FirstName]))) > 0");

                            t.HasCheckConstraint("CK_User_LastName_NotBlank", "LEN(LTRIM(RTRIM([LastName]))) > 0");

                            t.HasCheckConstraint("CK_User_MobileNumber", "[MobileNumber] LIKE '09%' AND LEN([MobileNumber]) = 11");

                            t.HasCheckConstraint("CK_User_PasswordHash_NotBlank", "LEN(LTRIM(RTRIM([PasswordHash]))) > 0");

                            t.HasCheckConstraint("CK_User_Role", "[Role] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.UserPermissionEntities", b =>
                {
                    b.Property<Guid>("FkUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Section")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Operations")
                        .HasColumnType("tinyint");

                    b.HasKey("FkUser", "Section");

                    b.ToTable("UserPermissionDs", t =>
                        {
                            t.HasCheckConstraint("CK_UserPermission_Operations", "[Operations] BETWEEN 1 AND 31");

                            t.HasCheckConstraint("CK_UserPermission_Section", "[Section] IN (1, 2, 3, 4, 5, 6, 7, 8)");
                        });
                });

            modelBuilder.Entity("RMS.Domain.Entities.AccidentEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.RoadsEntities", "Road")
                        .WithMany("AccountList")
                        .HasForeignKey("FkIdRoad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Road");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CarEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.AccidentEntities", "Accident")
                        .WithMany("CarList")
                        .HasForeignKey("FkAccident")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("RMS.Domain.Entities.ImageEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.AccidentEntities", "Accident")
                        .WithMany("ImageList")
                        .HasForeignKey("FkAccident")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("RMS.Domain.Entities.PassengerEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.CarEntities", "Car")
                        .WithMany("PassengerList")
                        .HasForeignKey("FkCar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RMS.Domain.Entities.PeopleEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.AccidentEntities", "Accident")
                        .WithMany("PeopleList")
                        .HasForeignKey("FkAccident")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("RMS.Domain.Entities.UserPermissionEntities", b =>
                {
                    b.HasOne("RMS.Domain.Entities.UserEntities", "User")
                        .WithMany("Permissions")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RMS.Domain.Entities.AccidentEntities", b =>
                {
                    b.Navigation("CarList");

                    b.Navigation("ImageList");

                    b.Navigation("PeopleList");
                });

            modelBuilder.Entity("RMS.Domain.Entities.CarEntities", b =>
                {
                    b.Navigation("PassengerList");
                });

            modelBuilder.Entity("RMS.Domain.Entities.RoadsEntities", b =>
                {
                    b.Navigation("AccountList");
                });

            modelBuilder.Entity("RMS.Domain.Entities.UserEntities", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
