// <auto-generated/>
using Microsoft.AspNetCore.Components.Authorization;
using RMS.Client.Services;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Layout;

public partial class MainLayout
{
    private bool sidebarCollapsed;
    private bool mobileMenuOpen;
    private UserResponse? CurrentUser => AuthenticationState.CurrentUser;

    protected override async Task OnInitializedAsync()
    {
        AuthenticationState.AuthenticationStateChanged += HandleAuthenticationStateChanged;
        try
        {
            await Authentication.RefreshCurrentUserAsync();
        }
        catch (ApiClientException)
        {
            // اطلاعات ذخیره‌شده نشست برای نمایش پوسته کافی است؛ خطای شبکه داخل صفحات نمایش داده می‌شود.
        }
        catch (HttpRequestException)
        {
            // در قطعی موقت API، نشست معتبر محلی حفظ می‌شود.
        }
    }

    private void HandleAuthenticationStateChanged(Task<AuthenticationState> authenticationStateTask) =>
        _ = InvokeAsync(StateHasChanged);

    private async Task LogoutAsync()
    {
        await Authentication.LogoutAsync();
        Navigation.NavigateTo("/login", replace: true);
    }

    private string GetDisplayName() => CurrentUser is null
        ? "کاربر سامانه"
        : $"{CurrentUser.FirstName} {CurrentUser.LastName}".Trim();

    private string GetInitials()
    {
        if (CurrentUser is null)
            return "ک";
        return $"{CurrentUser.FirstName.FirstOrDefault()}{CurrentUser.LastName.FirstOrDefault()}";
    }

    private string GetRoleLabel() => CurrentUser?.Role switch
    {
        UserRole.Administrator => "مدیر ارشد سامانه",
        UserRole.Manager => "مدیر",
        UserRole.User => "کاربر",
        _ => "حساب کاربری"
    };

    private void ToggleSidebar() => sidebarCollapsed = !sidebarCollapsed;
    private void OpenMobileMenu() => mobileMenuOpen = true;
    private void CloseMobileMenu() => mobileMenuOpen = false;

    public void Dispose() =>
        AuthenticationState.AuthenticationStateChanged -= HandleAuthenticationStateChanged;
}
