// <auto-generated/>
using Microsoft.JSInterop;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.Reports
{
    public partial class AccidentMapReport
    {
        private DateTime startDate = DateTime.Today.AddMonths(-1);
        private DateTime endDate = DateTime.Today;
        private bool isLoading, mapPending, mapRendered;
        private string? pageError;
        private readonly List<AccidentMapPointResponse> points = [];
        private bool CanAccess => AuthenticationState.HasPermission(UserSection.Accidents, UserAccessOperation.Report);
        protected override async Task OnInitializedAsync()
        {
            if (CanAccess)
                await SearchAsync();
        }
        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            if (!mapPending)
                return;
            mapPending = false;
            await JS.InvokeVoidAsync("rmsInterop.renderAccidentReportMap", "accident-report-map", points.Select(point => new MapPoint(
                point.Latitude,
                point.Longitude,
                $"ACC-{RmsUi.ShortId(point.Id)}",
                RmsUi.DateTime(point.AccidentTimeUnix)
            )).ToArray());
            mapRendered = true;
        }
        private async Task SearchAsync()
        {
            isLoading = true;
            pageError = null;
            try
            {
                points.Clear();
                points.AddRange(await AccidentApi.GetMapAsync(new AccidentMapQuery
                {
                    StartTime = StartUnix,
                    EndTime = EndUnix
                    ,
                    Take = int.MaxValue
                }));
                mapPending = true;
            }
            catch (Exception ex) when (ex is ApiClientException or HttpRequestException) { pageError = ex is ApiClientException api ? api.Message : "ارتباط با RMS.Api برقرار نشد."; }
            finally { isLoading = false; }
        }
        private long StartUnix => new DateTimeOffset(startDate.Date, TimeZoneInfo.Local.GetUtcOffset(startDate.Date)).ToUnixTimeSeconds();
        private long EndUnix => new DateTimeOffset(endDate.Date.AddDays(1).AddSeconds(-1), TimeZoneInfo.Local.GetUtcOffset(endDate.Date)).ToUnixTimeSeconds();
        private static string Persian(int value) => value.ToString("N0").TranslateDigits();
        public async ValueTask DisposeAsync()
        {
            if (mapRendered)
            {
                try
                {
                    await JS.InvokeVoidAsync("rmsInterop.disposeAccidentReportMap");
                }
                catch (JSDisconnectedException) { }
            }
        }
        private sealed record MapPoint(double Latitude, double Longitude, string Title, string Date);
    }
}
