// <auto-generated/>
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.Reports;

public partial class CarReport
{
    private const int PageSize = 25;
    private readonly List<CarListItemResponse> rows = [];
    private readonly HashSet<Guid> expandedRows = [];
    private string selectedAccident = string.Empty;
    private string plate = string.Empty;
    private string searchTerm = string.Empty;
    private string selectedClass = string.Empty;
    private int currentPage;
    private int totalCount;
    private bool isLoading;
    private bool hasSearched;
    private string? pageError;

    private bool CanAccess => AuthenticationState.HasPermission(UserSection.Reports, UserAccessOperation.Report)
        && AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);
    private int PageCount => Math.Max(1, (int)Math.Ceiling(totalCount / (double)PageSize));

    private async Task SearchAsync()
    {
        currentPage = 0;
        hasSearched = true;
        await LoadPageAsync();
    }

    private async Task LoadPageAsync()
    {
        isLoading = true;
        pageError = null;
        expandedRows.Clear();
        try
        {
            var result = await CarApi.GetAllAsync(new CarQueries
            {
                AccidentId = Guid.TryParse(selectedAccident, out var accidentId) ? accidentId : null,
                Plate = string.IsNullOrWhiteSpace(plate) ? null : plate.Trim(),
                SearchTerm = string.IsNullOrWhiteSpace(searchTerm) ? null : searchTerm.Trim(),
                CarClass = byte.TryParse(selectedClass, out var carClass) ? (CarClassEnums)carClass : null,
                Skip = currentPage * PageSize,
                Take = PageSize
            });
            rows.Clear();
            rows.AddRange(result.Items);
            totalCount = result.TotalCount;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            rows.Clear();
            totalCount = 0;
            pageError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با RMS.Api برقرار نشد. از اجرای سرویس مطمئن شوید.";
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task PreviousPageAsync()
    {
        if (currentPage == 0)
            return;
        currentPage--;
        await LoadPageAsync();
    }

    private async Task NextPageAsync()
    {
        if (currentPage >= PageCount - 1)
            return;
        currentPage++;
        await LoadPageAsync();
    }

    private void ClearFilters()
    {
        selectedAccident = string.Empty;
        plate = string.Empty;
        searchTerm = string.Empty;
        selectedClass = string.Empty;
        currentPage = 0;
        totalCount = 0;
        rows.Clear();
        expandedRows.Clear();
        pageError = null;
        hasSearched = false;
    }

    private void ToggleDetails(Guid id)
    {
        if (!expandedRows.Add(id))
            expandedRows.Remove(id);
    }

    private static string DamageTone(int damage) => damage >= 70 ? "danger" : damage >= 30 ? "warning" : "success";
    private static string Persian(int value) => value.ToString("N0").TranslateDigits();

    private async Task<IReadOnlyList<LookupOption>> SearchAccidentsAsync(string term, CancellationToken token) =>
        (await LookupApi.GetAccidentsAsync(new AccidentLookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(accident => new LookupOption(accident.Id.ToString(), $"{accident.RoadName} · {RmsUi.DateTime(accident.AccidentTimeUnix)}"))
            .ToArray();
}
