// <auto-generated/>
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.Reports;

public partial class HumanReport
{
    private const int PageSize = 25;
    private readonly List<HumanItemResponse> rows = [];
    private string nationalCode = string.Empty;
    private string selectedRole = string.Empty;
    private string selectedDamageType = string.Empty;
    private int currentPage;
    private int totalCount;
    private bool isLoading;
    private bool hasSearched;
    private string? pageError;

    private bool CanAccess => AuthenticationState.HasPermission(UserSection.Reports, UserAccessOperation.Report)
        && AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);
    private int PageCount => Math.Max(1, (int)Math.Ceiling(totalCount / (double)PageSize));

    private async Task SearchAsync()
    {
        currentPage = 0;
        hasSearched = true;
        await LoadPageAsync();
    }

    private async Task LoadPageAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            var result = await AnalyticsApi.GetHumanReportAsync(new HumanQueries
            {
                NationalCode = string.IsNullOrWhiteSpace(nationalCode) ? null : nationalCode.Trim(),
                IsDriver = bool.TryParse(selectedRole, out var isDriver) ? isDriver : null,
                DamageType = byte.TryParse(selectedDamageType, out var damageType) ? (DamageTypePersonEnum)damageType : null,
                Skip = currentPage * PageSize,
                Take = PageSize
            });
            rows.Clear();
            rows.AddRange(result.Items);
            totalCount = result.TotalCount;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            rows.Clear();
            totalCount = 0;
            pageError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با RMS.Api برقرار نشد.";
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task PreviousPageAsync()
    {
        if (currentPage == 0)
            return;
        currentPage--;
        await LoadPageAsync();
    }

    private async Task NextPageAsync()
    {
        if (currentPage >= PageCount - 1)
            return;
        currentPage++;
        await LoadPageAsync();
    }

    private void ClearFilters()
    {
        nationalCode = string.Empty;
        selectedRole = string.Empty;
        selectedDamageType = string.Empty;
        currentPage = 0;
        totalCount = 0;
        rows.Clear();
        pageError = null;
        hasSearched = false;
    }

    private static string Persian(int value) => value.ToString("N0").TranslateDigits();
}
