// <auto-generated/>
using System.Globalization;
using Microsoft.JSInterop;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.Reports;

public partial class Reports
{
    private AccidentReportResponse? report;
    private int rangeMonths = 12;
    private string selectedRoad = string.Empty;
    private string selectedType = string.Empty;
    private bool isLoading = true;
    private bool chartsPending;
    private bool chartsRendered;
    private string? pageError;

    private bool CanAccess => AuthenticationState.HasPermission(UserSection.Reports, UserAccessOperation.Report);
    private bool CanCarsReport => CanAccess && AuthenticationState.HasPermission(UserSection.Cars, UserAccessOperation.Report);
    private bool CanHumansReport => CanAccess && AuthenticationState.HasPermission(UserSection.People, UserAccessOperation.Report);
    private bool CanFilterByRoad => AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.Report);

    private string InsightText
    {
        get
        {
            if ((report?.AccidentCount ?? 0) == 0)
                return "در بازه و فیلتر انتخاب‌شده حادثه‌ای وجود ندارد.";
            var mainCause = report!.Causes.FirstOrDefault();
            var mainWeather = report.Weather.FirstOrDefault();
            if (mainCause is null || mainWeather is null)
                return "اطلاعات این بازه برای استخراج الگوی غالب کافی نیست.";
            return $"پرتکرارترین علت «{RmsUi.AccidentCause((AccidentCauseEnums)mainCause.Key)}» با {Persian(mainCause.Count)} رخداد است و بیشترین حوادث در وضعیت «{RmsUi.Weather((WeatherConditionEnums)mainWeather.Key)}» ثبت شده‌اند.";
        }
    }

    protected override async Task OnInitializedAsync()
    {
        if (!CanAccess)
        {
            isLoading = false;
            return;
        }

        try
        {
            await LoadReportAsync();
            chartsPending = true;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.";
        }
        finally
        {
            isLoading = false;
        }
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (!chartsPending)
            return;
        chartsPending = false;
        await JS.InvokeVoidAsync("rmsInterop.renderReportCharts", BuildChartData());
        chartsRendered = true;
    }

    private async Task ApplyFiltersAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadReportAsync();
            chartsPending = true;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = exception is ApiClientException apiException
                ? apiException.Message
                : "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.";
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadReportAsync()
    {
        var endTime = DateTimeOffset.UtcNow.AddSeconds(1);
        report = await AnalyticsApi.GetAccidentReportAsync(new AccidentReportQuery
        {
            StartTime = endTime.AddMonths(-rangeMonths).ToUnixTimeSeconds(),
            EndTime = endTime.ToUnixTimeSeconds(),
            Months = Math.Clamp(rangeMonths, 1, 24),
            RoadId = Guid.TryParse(selectedRoad, out var roadId) ? roadId : null,
            AccidentType = byte.TryParse(selectedType, out var type) ? (AccidentTypeEnums)type : null
        });
    }

    private async Task<IReadOnlyList<LookupOption>> SearchRoadsAsync(string term, CancellationToken token) =>
        (await LookupApi.GetRoadsAsync(new LookupQuery { SearchTerm = term, Take = 20 }, token))
            .Select(road => new LookupOption(road.Id.ToString(), road.Name))
            .ToArray();

    private ReportChartData BuildChartData()
    {
        var monthly = report?.MonthlyTrend ?? [];
        var types = report?.Types ?? [];
        var weather = report?.Weather ?? [];

        return new ReportChartData(
            monthly.Select(item => PersianMonthLabel(item.PeriodStartUnix)).ToArray(),
            monthly.Select(item => item.AccidentCount).ToArray(),
            monthly.Select(item => item.AverageInjury).ToArray(),
            types.Select(item => RmsUi.AccidentType((AccidentTypeEnums)item.Key)).ToArray(),
            types.Select(item => item.Count).ToArray(),
            weather.Select(item => RmsUi.Weather((WeatherConditionEnums)item.Key)).ToArray(),
            weather.Select(item => item.Count).ToArray());
    }

    private static string Persian(int value) => value.ToString("N0").TranslateDigits();

    private static string PersianMonthLabel(long unixTime)
    {
        var date = DateTimeOffset.FromUnixTimeSeconds(unixTime).ToLocalTime().DateTime;
        var calendar = new PersianCalendar();
        return $"{calendar.GetYear(date):0000}/{calendar.GetMonth(date):00}".TranslateDigits();
    }

    public async ValueTask DisposeAsync()
    {
        if (chartsRendered)
            await JS.InvokeVoidAsync("rmsInterop.destroyCharts");
    }

    private sealed record ReportChartData(
        string[] MonthLabels,
        int[] AccidentCounts,
        int[] AverageInjury,
        string[] TypeLabels,
        int[] TypeValues,
        string[] WeatherLabels,
        int[] WeatherValues);
}
