// <auto-generated/>
using System.Text.Json;
using Microsoft.AspNetCore.Components;
using Microsoft.JSInterop;
using NetTopologySuite.Geometries;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.BasicSettings;

public partial class Roads
{
    private const int RoadPageSize = 20;
    private readonly List<RoadListItemResponse> roads = [];
    private readonly List<RoadMapItemResponse> mapRoads = [];
    private string searchTerm = string.Empty;
    private int roadPageIndex;
    private int totalRoadCount;
    private CancellationTokenSource? roadQueryCancellation;
    private Guid? selectedRoadId;
    private bool isLoading = true;
    private string? pageError;
    private string? successMessage;
    private bool mapRefreshPending;

    private bool editorOpen;
    private bool isLoadingEditor;
    private bool isSaving;
    private bool editorMapPending;
    private int roadEditorPointCount;
    private int roadEditorPathCount;
    private int? selectedEditorPointIndex;
    private int? selectedEditorPathIndex;
    private DotNetObjectReference<Roads>? roadEditorReference;
    private Guid? editingRoadId;
    private string editorName = string.Empty;
    private IReadOnlyList<IReadOnlyList<MapPoint>> editorPaths = [];
    private string? editorError;
    private string roadSearchText = string.Empty;
    private bool isSearchingRoad;
    private bool searchPerformed;
    private string? selectedOsmGroup;
    private SearchResultGroup? selectedSearchResult;
    private string? searchError;
    private readonly List<OsmRoadSearchResult> searchResults = [];
    private RouteSelectionKind? routeSelectionKind;
    private OsmGeoPoint? routeSelectionStart;
    private OsmGeoPoint? routeSelectionEnd;
    private bool isRouting;
    private string? routeSelectionError;
    private string? routeSelectionSummary;

    private bool deleteOpen;
    private bool isDeleting;
    private RoadListItemResponse? deletingRoad;
    private string? deleteError;

    private bool CanList => AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.Report);
    private bool CanView => AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.View);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.Create);
    private bool CanUpdate => CanView && AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Roads, UserAccessOperation.Delete);
    private bool CanCalculateRoute => routeSelectionKind.HasValue &&
                                      routeSelectionStart is not null &&
                                      routeSelectionEnd is not null &&
                                      !isRouting;
    private int RoadPageCount => Math.Max(1, (int)Math.Ceiling(totalRoadCount / (double)RoadPageSize));
    private int RoadsWithAccidents => roads.Count(road => road.AccidentCount > 0);
    private List<SearchResultGroup> SearchResultGroups => searchResults
        .GroupBy(result => result.SuggestedName, StringComparer.OrdinalIgnoreCase)
        .Select(group => new SearchResultGroup(
            group.Key,
            group.First().DisplayName,
            group.ToArray(),
            group.Count() > 1
                ? $"{group.Count().ToString().TranslateDigits()} قطعه هم‌نام"
                : GeometryLabel(group.First().GeometryType)))
        .ToList();

    protected override async Task OnInitializedAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }
        await LoadAsync();
    }

    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if ((firstRender || mapRefreshPending) && CanList)
        {
            mapRefreshPending = false;
            await JS.InvokeVoidAsync("rmsInterop.renderRoadMap", "road-map", BuildRoadMapItems());
        }

        if (editorMapPending)
        {
            editorMapPending = false;
            roadEditorReference ??= DotNetObjectReference.Create(this);
            await JS.InvokeVoidAsync("rmsInterop.renderRoadEditorMap", "road-editor-map", editorPaths, roadEditorReference);
        }
    }

    private async Task LoadAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadRoadPageDataAsync(CancellationToken.None);
            await LoadRoadMapDataAsync(CancellationToken.None);


            selectedRoadId = roads.FirstOrDefault()?.Id;
            mapRefreshPending = true;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت راه‌ها از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task LoadRoadPageDataAsync(CancellationToken token)
    {
        var page = await RoadApi.GetAllAsync(new RoadQueries
        {
            Skip = roadPageIndex * RoadPageSize,
            Take = RoadPageSize,
            SearchTerm = searchTerm
        }, token);
        roads.Clear();
        roads.AddRange(page.Items);
        totalRoadCount = page.TotalCount;
        if (roadPageIndex >= RoadPageCount)
        {
            roadPageIndex = Math.Max(0, RoadPageCount - 1);
            page = await RoadApi.GetAllAsync(new RoadQueries
            {
                Skip = roadPageIndex * RoadPageSize,
                Take = RoadPageSize,
                SearchTerm = searchTerm
            }, token);
            roads.Clear();
            roads.AddRange(page.Items);
            totalRoadCount = page.TotalCount;
        }

    }

    private async Task LoadRoadMapDataAsync(CancellationToken token)
    {
        mapRoads.Clear();
        mapRoads.AddRange(await RoadApi.GetMapAsync(new RoadMapQuery
        {
            SearchTerm = searchTerm,
            Zoom = 9,
            Take = 500
        }, token));
    }

    private async Task OnRoadSearchInputAsync(ChangeEventArgs eventArgs)
    {
        searchTerm = eventArgs.Value?.ToString() ?? string.Empty;
        roadPageIndex = 0;
        roadQueryCancellation?.Cancel();
        roadQueryCancellation?.Dispose();
        roadQueryCancellation = new CancellationTokenSource();
        var token = roadQueryCancellation.Token;
        try
        {
            await Task.Delay(350, token);
            await ReloadRoadViewAsync(token);
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
    }

    private async Task PreviousRoadPageAsync()
    {
        roadPageIndex = Math.Max(0, roadPageIndex - 1);
        await ReloadRoadPageAsync();
    }

    private async Task NextRoadPageAsync()
    {
        roadPageIndex = Math.Min(RoadPageCount - 1, roadPageIndex + 1);
        await ReloadRoadPageAsync();
    }

    private async Task ReloadRoadPageAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadRoadPageDataAsync(CancellationToken.None);
            selectedRoadId = roads.FirstOrDefault()?.Id;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت فهرست راه‌ها از API با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task ReloadRoadViewAsync(CancellationToken token)
    {
        isLoading = true;
        pageError = null;
        try
        {
            await LoadRoadPageDataAsync(token);
            await LoadRoadMapDataAsync(token);
            selectedRoadId = roads.FirstOrDefault()?.Id;
            mapRefreshPending = true;
        }
        catch (OperationCanceledException) when (token.IsCancellationRequested)
        {
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = ErrorMessage(exception, "دریافت راه‌ها از API با خطا مواجه شد.");
        }
        finally
        {
            if (!token.IsCancellationRequested)
                isLoading = false;
        }
    }

    private async Task SelectRoadAsync(Guid id)
    {
        selectedRoadId = id;
        await JS.InvokeVoidAsync("rmsInterop.focusRoad", id.ToString());
    }

    private void OpenCreate()
    {
        editingRoadId = null;
        editorName = string.Empty;
        editorPaths = [];
        roadEditorPointCount = 0;
        roadEditorPathCount = 0;
        selectedEditorPointIndex = null;
        selectedEditorPathIndex = null;
        editorError = null;
        ResetRouteSelectionState();
        ResetRoadSearch();
        isLoadingEditor = false;
        editorOpen = true;
        editorMapPending = true;
    }

    private async Task OpenEditAsync(Guid id)
    {
        editorOpen = true;
        isLoadingEditor = true;
        editorError = null;
        editingRoadId = id;
        ResetRouteSelectionState();
        ResetRoadSearch();
        try
        {
            var road = await RoadApi.GetByIdAsync(id);
            editorName = road.Name;
            editorPaths = RoutePaths(road.Boundary);
            roadEditorPointCount = editorPaths.Sum(path => path.Count);
            roadEditorPathCount = editorPaths.Count;
            selectedEditorPointIndex = null;
            selectedEditorPathIndex = editorPaths.Count > 0 ? 0 : null;
            editorMapPending = true;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            editorError = ErrorMessage(exception, "دریافت اطلاعات مسیر با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private async Task SaveRoadAsync()
    {
        editorError = null;
        isSaving = true;
        try
        {
            if (string.IsNullOrWhiteSpace(editorName))
                throw new FormatException("نام راه یا مسیر الزامی است.");

            var paths = await JS.InvokeAsync<MapPoint[][]>("rmsInterop.getRoadEditorPaths");
            var validPaths = paths.Where(path => path.Length >= 2).ToArray();
            if (validPaths.Length == 0)
                throw new FormatException("حداقل یک مسیر با دو نقطه روی نقشه مشخص کنید.");

            var geometryFactory = new GeometryFactory(new PrecisionModel(), 4326);
            var route = geometryFactory.CreateMultiLineString(validPaths
                .Select(path => geometryFactory.CreateLineString(path
                    .Select(point => new Coordinate(point.Longitude, point.Latitude))
                    .ToArray()))
                .ToArray());
            var interiorPoint = route.InteriorPoint;
            interiorPoint.SRID = route.SRID;

            if (editingRoadId.HasValue)
            {
                await RoadApi.UpdateAsync(editingRoadId.Value, new UpdateRoadCommand
                {
                    Id = editingRoadId.Value,
                    Name = editorName.Trim(),
                    Boundary = route,
                    Centroid = interiorPoint
                });
                successMessage = "مسیر با موفقیت ویرایش شد.";
            }
            else
            {
                await RoadApi.CreateAsync(new CreateRoadCommand
                {
                    Name = editorName.Trim(),
                    Boundary = route,
                    Centroid = interiorPoint
                });
                successMessage = "مسیر با موفقیت ثبت شد.";
            }

            editorOpen = false;
            await JS.InvokeVoidAsync("rmsInterop.disposeRoadEditorMap");
            await LoadAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException or FormatException)
        {
            editorError = ErrorMessage(exception, "ذخیره مسیر با خطا مواجه شد.");
        }
        finally
        {
            isSaving = false;
        }
    }

    private async Task SearchRoadAsync()
    {
        searchError = null;
        searchPerformed = true;
        searchResults.Clear();
        selectedOsmGroup = null;
        selectedSearchResult = null;
        isSearchingRoad = true;
        try
        {
            searchResults.AddRange(await OsmSearch.SearchRoadsAsync(roadSearchText));
        }
        catch (Exception exception) when (exception is HttpRequestException or ArgumentException or JsonException)
        {
            searchError = exception is HttpRequestException
                ? "ارتباط با سرویس جست‌وجوی OpenStreetMap برقرار نشد. کمی بعد دوباره تلاش کنید."
                : exception.Message;
        }
        finally
        {
            isSearchingRoad = false;
        }
    }

    private async Task SelectSearchResultAsync(SearchResultGroup result)
    {
        searchError = null;
        try
        {
            editorPaths = RoadPathBuilder.CreatePaths(result.Items)
                .Select(path => (IReadOnlyList<MapPoint>)path
                    .Select(point => new MapPoint(point.Latitude, point.Longitude))
                    .ToArray())
                .ToArray();
            roadEditorPointCount = editorPaths.Sum(path => path.Count);
            roadEditorPathCount = editorPaths.Count;
            selectedEditorPointIndex = null;
            selectedEditorPathIndex = editorPaths.Count > 0 ? 0 : null;
            ResetRouteSelectionState();
            selectedOsmGroup = result.Name;
            selectedSearchResult = result;
            if (string.IsNullOrWhiteSpace(editorName))
                editorName = result.Name;
            editorMapPending = true;
            await InvokeAsync(StateHasChanged);
        }
        catch (Exception exception) when (exception is InvalidOperationException or ArgumentOutOfRangeException)
        {
            searchError = exception.Message;
        }
    }

    private void ResetRoadSearch()
    {
        roadSearchText = string.Empty;
        isSearchingRoad = false;
        searchPerformed = false;
        selectedOsmGroup = null;
        selectedSearchResult = null;
        searchError = null;
        searchResults.Clear();
    }

    private async Task ClearDrawingAsync() => await JS.InvokeVoidAsync("rmsInterop.clearRoadEditorDrawing");

    private async Task BeginRouteSelectionAsync(RouteSelectionKind selectionKind)
    {
        routeSelectionKind = selectionKind;
        routeSelectionStart = null;
        routeSelectionEnd = null;
        routeSelectionError = null;
        routeSelectionSummary = null;
        await JS.InvokeVoidAsync("rmsInterop.beginRoadRouteSelection");
    }

    private async Task CancelRouteSelectionAsync()
    {
        ResetRouteSelectionState();
        await JS.InvokeVoidAsync("rmsInterop.cancelRoadRouteSelection");
    }

    [JSInvokable]
    public Task OnRoadRoutePointSelected(double latitude, double longitude, int pointNumber)
    {
        if (!routeSelectionKind.HasValue || isRouting)
            return Task.CompletedTask;

        if (pointNumber == 1)
        {
            routeSelectionStart = new OsmGeoPoint(latitude, longitude);
            routeSelectionEnd = null;
        }
        else if (pointNumber == 2 && routeSelectionStart is not null)
        {
            routeSelectionEnd = new OsmGeoPoint(latitude, longitude);
        }

        return InvokeAsync(StateHasChanged);
    }

    private async Task CalculateSelectedRouteAsync()
    {
        if (!CanCalculateRoute ||
            routeSelectionKind is not { } selectedKind ||
            routeSelectionStart is null ||
            routeSelectionEnd is null)
            return;

        isRouting = true;
        routeSelectionError = null;
        routeSelectionSummary = null;
        try
        {
            var route = await OsmRouting.FindRouteAsync(
                routeSelectionStart,
                routeSelectionEnd);
            var points = route.Points
                .Select(point => new MapPoint(point.Latitude, point.Longitude))
                .ToArray();

            await JS.InvokeVoidAsync(
                selectedKind == RouteSelectionKind.Primary
                    ? "rmsInterop.setRoadEditorPrimaryPath"
                    : "rmsInterop.appendRoadEditorPath",
                (object)points);

            var distance = (route.DistanceMeters / 1000d).ToString("0.#").TranslateDigits();
            var duration = Math.Max(1, (int)Math.Ceiling(route.DurationSeconds / 60d))
                .ToString()
                .TranslateDigits();
            routeSelectionSummary = $"مسیر با طول تقریبی {distance} کیلومتر و زمان {duration} دقیقه به ویرایشگر اضافه شد.";
            routeSelectionKind = null;
            routeSelectionStart = null;
            routeSelectionEnd = null;
        }
        catch (Exception exception) when (exception is HttpRequestException or InvalidOperationException or JsonException or ArgumentOutOfRangeException or JSException)
        {
            routeSelectionError = exception switch
            {
                HttpRequestException => "ارتباط با سرویس مسیریابی برقرار نشد. کمی بعد دوباره تلاش کنید.",
                JSException => "مسیر محاسبه شد، اما رسم نقاط روی نقشه با خطا مواجه شد.",
                _ => exception.Message
            };
        }
        finally
        {
            isRouting = false;
        }
    }

    private void ResetRouteSelectionState()
    {
        routeSelectionKind = null;
        routeSelectionStart = null;
        routeSelectionEnd = null;
        isRouting = false;
        routeSelectionError = null;
        routeSelectionSummary = null;
    }

    private async Task AddPathAsync() => await JS.InvokeVoidAsync("rmsInterop.addRoadEditorPath");

    private async Task DeleteSelectedPathAsync() =>
        await JS.InvokeVoidAsync("rmsInterop.deleteSelectedRoadEditorPath");

    private async Task DeleteSelectedPointAsync() =>
        await JS.InvokeVoidAsync("rmsInterop.deleteSelectedRoadEditorPoint");

    private async Task RemoveLastPointAsync() =>
        await JS.InvokeVoidAsync("rmsInterop.removeLastRoadEditorPoint");

    [JSInvokable]
    public Task OnRoadEditorChanged(
        int pointCount,
        int? selectedIndex,
        int pathCount,
        int? selectedPathIndex)
    {
        roadEditorPointCount = pointCount;
        selectedEditorPointIndex = selectedIndex;
        roadEditorPathCount = pathCount;
        selectedEditorPathIndex = selectedPathIndex;
        return InvokeAsync(StateHasChanged);
    }

    private async Task CloseEditorAsync()
    {
        if (isSaving)
            return;
        ResetRouteSelectionState();
        editorOpen = false;
        await JS.InvokeVoidAsync("rmsInterop.disposeRoadEditorMap");
    }

    private void AskDelete(RoadListItemResponse road)
    {
        deletingRoad = road;
        deleteError = null;
        deleteOpen = true;
    }

    private void CloseDelete()
    {
        if (!isDeleting)
            deleteOpen = false;
    }

    private async Task DeleteRoadAsync()
    {
        if (deletingRoad is null)
            return;
        isDeleting = true;
        deleteError = null;
        try
        {
            await RoadApi.DeleteAsync(deletingRoad.Id);
            deleteOpen = false;
            successMessage = "مسیر با موفقیت حذف شد.";
            await LoadAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            deleteError = ErrorMessage(exception, "حذف مسیر با خطا مواجه شد.");
        }
        finally
        {
            isDeleting = false;
        }
    }

    private RoadMapItem[] BuildRoadMapItems() => mapRoads.Select(road => new RoadMapItem(
        road.Id.ToString(), road.Name, RoutePaths(road.Boundary))).ToArray();

    private static IReadOnlyList<IReadOnlyList<MapPoint>> RoutePaths(Geometry geometry)
    {
        static IReadOnlyList<MapPoint> Convert(Coordinate[] coordinates)
        {
            if (coordinates.Length > 1 && coordinates[0].Equals2D(coordinates[^1]))
                coordinates = coordinates[..^1];
            return coordinates
                .Select(coordinate => new MapPoint(coordinate.Y, coordinate.X))
                .ToArray();
        }

        return geometry switch
        {
            LineString lineString => [Convert(lineString.Coordinates)],
            MultiLineString multiLineString => Enumerable.Range(0, multiLineString.NumGeometries)
                .Select(index => (IReadOnlyList<MapPoint>)Convert(
                    ((LineString)multiLineString.GetGeometryN(index)).Coordinates))
                .ToArray(),
            Polygon polygon => [Convert(polygon.ExteriorRing.Coordinates)],
            MultiPolygon multiPolygon => Enumerable.Range(0, multiPolygon.NumGeometries)
                .Select(index => (IReadOnlyList<MapPoint>)Convert(
                    ((Polygon)multiPolygon.GetGeometryN(index)).ExteriorRing.Coordinates))
                .ToArray(),
            _ => [Convert(geometry.Coordinates)]
        };
    }

    private static string ErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ when !string.IsNullOrWhiteSpace(exception.Message) => exception.Message,
        _ => fallback
    };

    private static string GeometryLabel(string geometryType) => geometryType switch
    {
        "LineString" => "مسیر خطی",
        "MultiLineString" => "مسیر چندبخشی",
        "Polygon" => "محدوده",
        "MultiPolygon" => "چند محدوده",
        _ => geometryType
    };

    public async ValueTask DisposeAsync()
    {
        roadQueryCancellation?.Cancel();
        roadQueryCancellation?.Dispose();
        try
        {
            await JS.InvokeVoidAsync("rmsInterop.disposeRoadMaps");
        }
        catch (JSDisconnectedException)
        {
        }
        roadEditorReference?.Dispose();
        roadEditorReference = null;
    }

    private sealed record MapPoint(double Latitude, double Longitude);
    private enum RouteSelectionKind
    {
        Primary, Branch
    }
    private sealed record RoadMapItem(string Id, string Name, IReadOnlyList<IReadOnlyList<MapPoint>> Paths);
    private sealed record SearchResultGroup(
        string Name,
        string Description,
        IReadOnlyList<OsmRoadSearchResult> Items,
        string Summary);
}
