// <auto-generated/>
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;
using RMS.Client.Models;
using RMS.Client.Services;
using RMS.Shared.Contracts.Commands;
using RMS.Shared.Contracts.Queries;
using RMS.Shared.Contracts.Responses;
using RMS.Shared.Enums;

namespace RMS.Client.Pages.BasicSettings;

public partial class Users
{
    private const int PageSize = 20;
    private readonly List<UserListItemResponse> users = [];
    private readonly Dictionary<UserSection, UserAccessOperation> editorPermissions = [];
    private AccessMetadataResponse? metadata;
    private UserEditorModel editor = new();
    private Guid? editingUserId;
    private UserListItemResponse? deletingUser;
    private string searchTerm = string.Empty;
    private UserRole? roleFilter;
    private int pageIndex;
    private int totalCount;
    private bool hasNextPage;
    private bool isLoading = true;
    private bool editorOpen;
    private bool isLoadingEditor;
    private bool isSaving;
    private bool deleteModalOpen;
    private bool isDeleting;
    private string? pageError;
    private string? successMessage;
    private string? editorError;
    private string? deleteError;

    private bool CanList => AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.Report);
    private bool CanView => AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.View);
    private bool CanCreate => AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.Create);
    private bool CanUpdate => AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.View)
        && AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.Update);
    private bool CanDelete => AuthenticationState.HasPermission(UserSection.Users, UserAccessOperation.Delete);
    private bool CanSaveEditor => editingUserId.HasValue ? CanUpdate : CanCreate;
    private int PageCount => Math.Max(1, (int)Math.Ceiling(totalCount / (double)PageSize));

    private IEnumerable<UserRole> AvailableRoles => metadata?.Roles
        .Select(item => (UserRole)item.Id)
        .Where(Enum.IsDefined) ?? Enum.GetValues<UserRole>();

    private IEnumerable<UserSection> AvailableSections => metadata?.Sections
        .Select(item => (UserSection)item.Id)
        .Where(Enum.IsDefined) ?? [];

    private IEnumerable<UserAccessOperation> AvailableOperations => metadata?.Operations
        .Select(item => (UserAccessOperation)item.Id)
        .Where(operation => operation != UserAccessOperation.None) ?? [];

    protected override async Task OnInitializedAsync()
    {
        if (!CanList)
        {
            isLoading = false;
            return;
        }

        await LoadMetadataAsync();
        await LoadUsersAsync();
    }

    private async Task LoadMetadataAsync()
    {
        if (!CanView)
            return;

        try
        {
            metadata = await UserApi.GetAccessMetadataAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = GetErrorMessage(exception, "دریافت نقش‌ها و دسترسی‌ها با خطا مواجه شد.");
        }
    }

    private async Task LoadUsersAsync()
    {
        isLoading = true;
        pageError = null;
        try
        {
            var result = await UserApi.GetAllAsync(new UserQuery
            {
                SearchTerm = searchTerm,
                Role = roleFilter,
                Skip = pageIndex * PageSize,
                Take = PageSize
            });
            users.Clear();
            users.AddRange(result.Items);
            totalCount = result.TotalCount;
            hasNextPage = (pageIndex + 1) * PageSize < totalCount;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            pageError = GetErrorMessage(exception, "دریافت فهرست کاربران با خطا مواجه شد.");
        }
        finally
        {
            isLoading = false;
        }
    }

    private async Task ReloadAsync()
    {
        successMessage = null;
        await LoadUsersAsync();
    }

    private async Task ApplyFiltersAsync()
    {
        pageIndex = 0;
        successMessage = null;
        await LoadUsersAsync();
    }

    private async Task HandleSearchKeyDown(KeyboardEventArgs args)
    {
        if (args.Key == "Enter")
            await ApplyFiltersAsync();
    }

    private async Task PreviousPageAsync()
    {
        if (pageIndex == 0)
            return;
        pageIndex--;
        await LoadUsersAsync();
    }

    private async Task NextPageAsync()
    {
        if (!hasNextPage)
            return;
        pageIndex++;
        await LoadUsersAsync();
    }

    private void OpenCreate()
    {
        editor = new UserEditorModel { Role = UserRole.User };
        editingUserId = null;
        editorPermissions.Clear();
        editorError = metadata is null ? "اطلاعات نقش‌ها و دسترسی‌ها هنوز از API دریافت نشده است." : null;
        isLoadingEditor = false;
        editorOpen = true;
    }

    private async Task OpenEditAsync(Guid id)
    {
        editorOpen = true;
        isLoadingEditor = true;
        editorError = null;
        editingUserId = id;
        editorPermissions.Clear();
        try
        {
            var user = await UserApi.GetByIdAsync(id);
            editor = new UserEditorModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                MobileNumber = user.MobileNumber,
                Role = user.Role
            };
            foreach (var permission in user.Permissions)
                editorPermissions[permission.Section] = permission.Operations;
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            editorError = GetErrorMessage(exception, "دریافت اطلاعات کاربر با خطا مواجه شد.");
        }
        finally
        {
            isLoadingEditor = false;
        }
    }

    private void CloseEditor()
    {
        if (!isSaving)
            editorOpen = false;
    }

    private async Task SaveUserAsync()
    {
        editorError = ValidatePasswords();
        if (editorError is not null)
            return;

        isSaving = true;
        try
        {
            var permissions = editorPermissions
                .Where(item => item.Value != UserAccessOperation.None)
                .Select(item => new UserPermissionCommand { Section = item.Key, Operations = item.Value })
                .ToArray();

            if (editingUserId.HasValue)
            {
                await UserApi.UpdateAsync(editingUserId.Value, new UpdateUserCommand
                {
                    Id = editingUserId.Value,
                    FirstName = editor.FirstName,
                    LastName = editor.LastName,
                    MobileNumber = editor.MobileNumber,
                    Password = string.IsNullOrWhiteSpace(editor.Password) ? null : editor.Password,
                    Role = editor.Role,
                    Permissions = permissions
                });

                if (AuthenticationState.CurrentUser?.Id == editingUserId.Value)
                    await Authentication.RefreshCurrentUserAsync();
                successMessage = "اطلاعات کاربر با موفقیت ویرایش شد.";
            }
            else
            {
                await UserApi.CreateAsync(new CreateUserCommand
                {
                    FirstName = editor.FirstName,
                    LastName = editor.LastName,
                    MobileNumber = editor.MobileNumber,
                    Password = editor.Password!,
                    Role = editor.Role,
                    Permissions = permissions
                });
                pageIndex = 0;
                successMessage = "کاربر جدید با موفقیت ثبت شد.";
            }

            editorOpen = false;
            await LoadUsersAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            editorError = GetErrorMessage(exception, "ذخیره اطلاعات کاربر با خطا مواجه شد.");
        }
        finally
        {
            isSaving = false;
        }
    }

    private string? ValidatePasswords()
    {
        if (!editingUserId.HasValue && string.IsNullOrWhiteSpace(editor.Password))
            return "برای کاربر جدید وارد کردن رمز عبور الزامی است.";
        if (!string.IsNullOrWhiteSpace(editor.Password) && editor.Password.Length < 6)
            return "رمز عبور باید حداقل ۶ کاراکتر داشته باشد.";
        if (!string.Equals(editor.Password, editor.ConfirmPassword, StringComparison.Ordinal))
            return "رمز عبور و تکرار آن یکسان نیستند.";
        return null;
    }

    private void AskDelete(UserListItemResponse user)
    {
        deletingUser = user;
        deleteError = null;
        deleteModalOpen = true;
    }

    private void CloseDeleteModal()
    {
        if (!isDeleting)
            deleteModalOpen = false;
    }

    private async Task DeleteUserAsync()
    {
        if (deletingUser is null)
            return;

        isDeleting = true;
        deleteError = null;
        try
        {
            await UserApi.DeleteAsync(deletingUser.Id);
            deleteModalOpen = false;
            successMessage = "کاربر با موفقیت حذف شد.";
            if (users.Count == 1 && pageIndex > 0)
                pageIndex--;
            await LoadUsersAsync();
        }
        catch (Exception exception) when (exception is ApiClientException or HttpRequestException)
        {
            deleteError = GetErrorMessage(exception, "حذف کاربر با خطا مواجه شد.");
        }
        finally
        {
            isDeleting = false;
        }
    }

    private bool HasEditorPermission(UserSection section, UserAccessOperation operation) =>
        editorPermissions.TryGetValue(section, out var current) && (current & operation) == operation;

    private bool HasAllEditorPermissions(UserSection section) =>
        AvailableOperations.All(operation => HasEditorPermission(section, operation));

    private void SetEditorPermission(UserSection section, UserAccessOperation operation, bool enabled)
    {
        var current = editorPermissions.GetValueOrDefault(section, UserAccessOperation.None);
        var updated = enabled ? current | operation : current & ~operation;
        if (updated == UserAccessOperation.None)
            editorPermissions.Remove(section);
        else
            editorPermissions[section] = updated;
    }

    private void SetAllEditorPermissions(UserSection section, bool enabled)
    {
        if (!enabled)
        {
            editorPermissions.Remove(section);
            return;
        }
        editorPermissions[section] = AvailableOperations.Aggregate(
            UserAccessOperation.None,
            (current, operation) => current | operation);
    }

    private static bool IsChecked(ChangeEventArgs args) => args.Value is true;

    private static string GetErrorMessage(Exception exception, string fallback) => exception switch
    {
        ApiClientException apiException => apiException.Message,
        HttpRequestException => "ارتباط با RMS.Api برقرار نشد. از اجرا بودن سرویس مطمئن شوید.",
        _ => fallback
    };

    private static string GetInitials(UserListItemResponse user) =>
        $"{user.FirstName.FirstOrDefault()}{user.LastName.FirstOrDefault()}";

    private static string GetUserSubtitle(UserListItemResponse user) =>
        user.Id == Guid.Empty ? "" : $"شناسه: {user.Id.ToString()[..8]}";

    private static string GetRoleLabel(UserRole role) => role switch
    {
        UserRole.Administrator => "مدیر ارشد",
        UserRole.Manager => "مدیر",
        _ => "کاربر"
    };

    private static string GetRoleTone(UserRole role) => role switch
    {
        UserRole.Administrator => "administrator",
        UserRole.Manager => "manager",
        _ => "user"
    };

    private static string GetSectionLabel(UserSection section) => section switch
    {
        UserSection.Users => "کاربران",
        UserSection.Roads => "راه‌ها و محدوده‌ها",
        UserSection.Accidents => "حوادث",
        UserSection.Cars => "خودروها",
        UserSection.Passengers => "رانندگان و سرنشینان",
        UserSection.People => "عابر",
        UserSection.Images => "تصاویر",
        UserSection.Reports => "گزارش‌ها",
        _ => section.ToString()
    };

    private static string GetSectionIcon(UserSection section) => section switch
    {
        UserSection.Users => "bi-people",
        UserSection.Roads => "bi-map",
        UserSection.Accidents => "bi-exclamation-octagon",
        UserSection.Cars => "bi-car-front",
        UserSection.Passengers => "bi-person-vcard",
        UserSection.People => "bi-person-walking",
        UserSection.Images => "bi-images",
        UserSection.Reports => "bi-bar-chart-line",
        _ => "bi-grid"
    };

    private static string GetOperationLabel(UserAccessOperation operation) => operation switch
    {
        UserAccessOperation.View => "مشاهده",
        UserAccessOperation.Create => "ثبت",
        UserAccessOperation.Update => "ویرایش",
        UserAccessOperation.Delete => "حذف",
        UserAccessOperation.Report => "گزارش",
        _ => operation.ToString()
    };

    private static string ToPersian(int value) => value.ToString().TranslateDigits();

    private sealed class UserEditorModel
    {
        [Required(ErrorMessage = "نام کاربر الزامی است."), MaxLength(50, ErrorMessage = "نام حداکثر ۵۰ کاراکتر است.")]
        public string FirstName { get; set; } = string.Empty;

        [Required(ErrorMessage = "نام خانوادگی الزامی است."), MaxLength(50, ErrorMessage = "نام خانوادگی حداکثر ۵۰ کاراکتر است.")]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "شماره موبایل الزامی است."), RegularExpression(@"^09\d{9}$", ErrorMessage = "شماره موبایل باید با 09 آغاز شود و ۱۱ رقم باشد.")]
        public string MobileNumber { get; set; } = string.Empty;

        public string? Password
        {
            get; set;
        }
        public string? ConfirmPassword
        {
            get; set;
        }
        public UserRole Role { get; set; } = UserRole.User;
    }
}
